### ISSUE TITLE
AutoLinks generates incorrect HTML when the same hyperlink occurs twice or more often in same text (patch).

### ISSUE THREAD

**Issue by monty241** [ActiveForums/ActiveForums#103]
When you have a text like

```
http://x.y.z/a/b/c
http://x.y.z/a/b/c
http://x.y.z/a/b/c
```

the automatic creation of links will generate incorrect HTML. It will generate something like:

<a href="<a href="<a href="...
<a href="<a href="<a href="...
<a href="<a href="<a href="...

because of the following code in Utilities.cs:

text = text.Replace(m.Value, url.ToLowerInvariant().Contains(currentSite.ToLowerInvariant()) ? string.Format(inSite, url, urlText) : string.Format(outSite, url, urlText));

This replace is executed once for every match on the regular expression for automatic hyperlink insertion. However, it does not replace the first match, but all occurrences of m.Value, leading to an extra expansion for autolinks for each duplicate hyperlink in a text.
##

**Comment by artfuld** [comment]
Including this in the new release. Closing thread
