### ISSUE TITLE
Can´t Upload File in Active Forums

### ISSUE THREAD

**Issue by claudioalmeida** [ActiveForums/ActiveForums#120]
Greetings, 

I´m a beginner in DNN and AF so forgive me if it is a silly thing. I have implemented DNN and AF on my company and it was working perfectly, including the attachs in AF. However, after updatinf AF, you cannot upload files on a topic anymore. You can "Choose File" but then I got the error:

POST (mysite)/DesktopModules/ActiveForums/API/ForumService/UploadFile 404 (Not Found) 

My DNN version is 07.01.01 and the AF version is 5.1.4. 

Thank you guys

**Comment by artfuld** [comment]
@claudioalmeida sorry for the late answer, do you still have this or a similar problem?
