### ISSUE TITLE
Delete forum group leaves gap in sort order - moving sort breaks

### ISSUE THREAD

**Issue by supermansrf** [ActiveForums/ActiveForums#122]
So I know what the problem is and what problems it creates, but not sure how to fix it.  I will eventually see if i can find a fix.  

When/if you delete a forum group, the sort order that deleted group occupied wasn't deleted, leaving a gap.  After you delete and if you try to sort any other groups around this, the button (up/down) arrow doesn't work.  Once you go into activeforums.groups and manually change the forum sort order the up/down arrows will again work.  Basically deleting the group needs to realign the sort ID from the groups above the deleted one (numerically).  

Again you can manually adjust the sort order and fix this.  I'll see if I can find a resolution to this one.

**Comment by supermansrf** [comment]
This still isn't fixed unless you have something up your sleeve :-)

**Comment by artfuld** [comment]
As someone talked about the sp Forums_RepairSort I figured someone had
allready taken the time to combine the two sp's.

Will fix that sp Forums_Delete to runt the sp forums_repairsort efter it
has removed the forums.

2015-08-09 19:39 GMT+02:00 Seth Folickman <notifications@github.com>:
