### ISSUE TITLE
Email template question

### ISSUE THREAD

**Issue by supermansrf** [ActiveForums/ActiveForums#131]
I touched on this a bit when I discussed another issue, but I want to bring it up again.

Does anyone know where on earth the template for the "alert" button is?  What I'm referring to is the email that goes to the admins when someone clicks the alert button to report a post.  

What I find odd is that nowhere does it say who reported it.  Only the profile photo of who reported it.  I would like to edit this to show the username or display name of who reported it.

**Comment by artfuld** [comment]
Closing this, guessing you found it out by now :).
Otherwise controls/af_modreport.ascx
