### ISSUE TITLE
Active Forums Development Environment Setup Thread

### ISSUE THREAD

**Issue by jbrunken** [ActiveForums/ActiveForums#14]
If you want to contribute to the project but you have questions about [setting up your development environment](https://github.com/jbrunken/ActiveForums/wiki/Setting-Up-your-Active-Forum-Development-Environment).  Please post them here.
##

**Comment by johnhenley** [comment]
Is the wiki article still accurate on dev environment, in regards to using VS 2012 and building against DNN 7.0?

Or can we use VS2013 and build against DNN 7.3.3 or 7.4 ?

**Comment by artfuld** [comment]
Seems accurate.
I usually do like this
Set up DNN on localhost.
take the latest version of AF (don't need source-code) on localhost.
Copy the files from my fork to the directory af is set up in (c:\inetpub\dnndev\desktopmodules\activeforums)
