### ISSUE TITLE
Group ID and Sub Forums

### ISSUE THREAD

**Issue by teambound** [ActiveForums/ActiveForums#155]
Hello Seth

Thanks for you work on this module! I have an urgent request. I use active forums in a group setting and it is an important module for us. Prior to upgrading to version 6 of forums I was at least able to reply to a topic post within a group without losing the groupid in the url and getting the sample group. Now I cannot post a reply without losing the groupid in the url. So I am at a stand still.

Also I created a sub forum and any activity in that also loses the groupid in the url.

I know @peppertree has done some work in this area and I wonder if his changes were merged in with the 6 build.

I know everyone is very busy and this is a volunteer effort but would appreciate any help here. We are launching a new date sensitive group and need the capability as soon as possible.

Thanks

Carl
##

**Comment by artfuld** [comment]
@teambound Have you tried the latest release yet?

**Comment by teambound** [comment]
Will take a look today
