### ISSUE TITLE
6.1 Beta 1 Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Plumifrons** [ActiveForums/ActiveForums#178]
DNN: 07.03.03
Update AF 4 to 5.2.2 to 6.1
I get an error viewing some (not all) topics.

ModuleId:654

ModuleDefId:225

FriendlyName:Gifkikkerportaal forum

ModuleControlSource:DesktopModules/ActiveForums/ActiveForums.ascx

AssemblyVersion:7.3.3

PortalID:0

PortalName:Gifkikkerportaal

UserID:5413

UserName:HostHan

ActiveTabID:96

ActiveTabName:Forum

RawURL:/Forum/tabid/96/aft/57009/Default.aspx

AbsoluteURL:/Default.aspx

AbsoluteURLReferrer:http://gifkikkerportaal/Forum/tabid/96/ctl/Login/Default.aspx?returnurl=%2fForum%2ftabid%2f96%2faft%2f57009%2fDefault.aspx

UserAgent:Mozilla/5.0 (Windows NT 6.3; WOW64; rv:33.0) Gecko/20100101 Firefox/33.0

DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke

ExceptionGUID:e4a1b9ae-8468-45f2-ae5a-2563c822a3b6

InnerException:Object reference not set to an instance of an object.

FileName:

FileLineNumber:0

FileColumnNumber:0

Method:DotNetNuke.Modules.ActiveForums.Controls.TopicView.ParseContent

StackTrace:

Message:

DotNetNuke.Services.Exceptions.ModuleLoadException: Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at DotNetNuke.Modules.ActiveForums.Controls.TopicView.ParseContent(DataRow dr, String tempate, Int32 rowcount)
   at DotNetNuke.Modules.ActiveForums.Controls.TopicView.ParseTopic(String sOutput)
   at DotNetNuke.Modules.ActiveForums.Controls.TopicView.BindTopic()
   at DotNetNuke.Modules.ActiveForums.Controls.TopicView.OnLoad(EventArgs e)
   --- End of inner exception stack trace ---
##

**Comment by frozendnn** [comment]
I am getting these errors with the latest AF build. Was this resolved? Thanks.
