### ISSUE TITLE
Active forum:Can't post questions with in a forum

### ISSUE THREAD

**Issue by kapilgobi** [ActiveForums/ActiveForums#183]
sir,
      i have one doubt in active forum.. i deployed Active forum6.1.0 in my dnn version 7.3.2.. here i can create gorup.. but i can't add questions with in a group..
 when i click on group heading i can see one form in that i given some details then i click save button page is loaded but my question is not saved with in a group  can u help me..
##

**Comment by artfuld** [comment]
This sounds like the same as #189 
Are you still having this problem?
