### ISSUE TITLE
Posting Topics / Quetions on Active forum 6.1.0 in DNN Cloud (Evoq) version 7.3.3

### ISSUE THREAD

**Issue by GunaKuppusamy** [ActiveForums/ActiveForums#189]
Hello there,

I need a help to solve an issue with Active forum. I've deployed Active forum 6.1.0 in one of our client's DNN Cloud (Evoq) version 7.3.3. 

After installation, I can create group but I can't add questions / Topics with in a group. When I click on group heading, I can see a form and I've entered some details then I clicked SAVE button. The page is getting loaded but my question is NOT saved with in a group.

It would be great if someone could help me on why I'm not able to post / save the questions / topics.

Thanks for your help.
##

**Comment by artfuld** [comment]
@GunaKuppusamy do you still have this problem? Sorry for the late answer.
