### ISSUE TITLE
Images uploading via HTML Editor (DotNetNuke RadEditorProvider) to separate folders for each user

### ISSUE THREAD

**Issue by maduranga001** [ActiveForums/ActiveForums#211]
I am using HTMLEditor to post forum posts and repllies. I need to give them to ability to upload files/images through the Image manager in the DotNetNuke RadEditorProvider. But all users have to upload the files in to a one folder (ActiveForums_Upload). There is no folder for each user and other users can see the uploaded files too. The worst case is ther users will replace the images by the same name images and also they can delete too.
Please advise. 
I am using DNN 7.3.4 and AF 5.3

What will be the solution for this?
##

**Comment by artfuld** [comment]
I'm not sure this is something activeforums is responsible for.

I use CK-editor on my site and has set it up to "Use subdirs for non admins", don't know if such setting exists for radeditor.
![image](https://cloud.githubusercontent.com/assets/6116748/5594934/8f2e76a8-9264-11e4-914c-d5f869315f1f.png)

**Comment by maduranga001** [comment]
Thank you for the reply. Can i use this editor? I have only one editor in the HTMLEditorProvider. Thanks!

**Comment by artfuld** [comment]
https://dnnckeditor.codeplex.com/

You need to install it on your site.

**Comment by maduranga001** [comment]
Thank you. Installed this and seems it fits my requirement. Thank You very much for the support.
