### ISSUE TITLE
User Levels and display in the profile

### ISSUE THREAD

**Issue by maduranga001** [ActiveForums/ActiveForums#212]
Hi,

I need to give different user levels apart from the posts like "VIP Members", "Gold Members" and "Staff members". They will have different access levels and permission levels in the site.
I need to display their user level(s) in the forum posts in the left side profile info. How can I do this? Please can you advise me for this?

Thank You!
##

**Comment by supermansrf** [comment]
There are 2 ways of doing what you are talking about.  One is based on the number of posts a user has.  Its the user ranks.  You can even customize the graphic that is used if necessary.  

Another way is manually using a profile property.  Create a new profile property calling it whatever you want.  Make it a list.  Assign the list the values that you want.  You will have to decide if the user will be able to edit this property or if admins only.  Set its visibility and assign your users the appropriate "level".  

Then in your ProfileInfo template, somewhere you will need to add the property to display.  The correct token is [DNN:PROFILE:Propertyname]

Hope this helps

**Comment by supermansrf** [comment]
I'm not 100% certain but I believe that token is case sensitive.  I have all mine listed exactly as I typed it, everything is all caps except for the last part which is first letter capital or whatever matches your property name.  I have one called [DNN:PROFILE:Chapters] and another called [DNN:PROFILE:OBSkill] both match the case of the original property name.

**Comment by maduranga001** [comment]
Great. Thanks! I will try this now and will come back if I have any problems. Really appreciate your support.

**Comment by maduranga001** [comment]
Hi. 

This is working. But a small issue.
I used list type custom property with a default value. Only admin shouldchange the value to another.
The problem is, the custom list property is not available for host account. super users. 

Please can you advise me how to load this in the profile to the superusers as well. I am loading a picture with the same name and can not leave it blank as it is loading a no-image link.

Appreciate your support. Thanks!
