### ISSUE TITLE
Display a forum view in two pages (2 AF modules in 2 different pages for one forum)

### ISSUE THREAD

**Issue by maduranga001** [ActiveForums/ActiveForums#217]
I am using AF 5.2.2 and installed 6.1.3. But gave me error and not installed properly. So I restored the backup site. So I am again in 5.2.2

This is my question.

I need to display one forum view in the home page which is with the active topics. Can I do this? Default view for active topics for last 24 hours. It should load by default without clicking the 'active topics' link.

I need the forum defaul folder view in the forum page. But the same forum. I did try to add two modules. But it is working as two different forums. How can I use this in two pages?

I like if I can list the last 24 hours posts in the home page and if somebody commented in any topic, it should come first. Is this available? Can I do this?

I really appreciate if you can advise me about this.

If I can load exactly what I can see in /Forum/afv/grid/afgt/activetopics/ts/80640 will be the best.
That is the view I need. If I can load directly this in the home page, That will be the best.
Is there a way to do this to load that view?

Thank you.
##

**Comment by artfuld** [comment]
Closing. Same as #414
