### ISSUE TITLE
Get last comments Post list without repeated post items.

### ISSUE THREAD

**Issue by maduranga001** [ActiveForums/ActiveForums#220]
Hi,

I am using AF 5.2.4 on DNN 7.3.4. I appreciate for giving this fantastic module as an ope source module. This is really great.

I need to display a list of posts in the home page once any user commented out in a post. I think I can use "What's New" module by uncheck the "Topics Only" check box. But it is listing the list with same repeat itms too. That mean if if 2 users commented to a same thread then it is displaying twice in the list.

Please can you advise how to sort this out? I need to display it once with the latest set of topics only once. Not so many times in a list. Probably this will be possible with an SQL update and I appreacite if you can help with this. If you can provide me an SQL Script, I m very happy.

Thank You very much for giving a brilliant module.
##

**Comment by frozendnn** [comment]
Not possible in the new version. However, it was possible in the  old version.

**Comment by artfuld** [comment]
Closing. Copy of #225
