### ISSUE TITLE
Time Zone Issue

### ISSUE THREAD

**Issue by maduranga001** [ActiveForums/ActiveForums#223]
The time using in the AF is the server time or something like that. I change host settings,Admin settings and host account setting to my local time zone. But it is not using the currect time zone.

Please advise me how to change to the correct time zone to my AF posts date time

Appreciete your suport.

Thank You!

**Comment by supermansrf** [comment]
AF displays the time based on the users time zone. Make sure that your
server time is correct (if you can set that) make sure your site time
zone matches the server (again if you can tell). Then user time zone
will adjust based on that users time zone. We haven't had an issue
with this for quite a while now. If I remember correctly it was back
in early version 5 and not across the board. Had a lot more to do with
dnn. I may even be wrong on this as I was using 2 different forums
back then.

**Comment by maduranga001** [comment]
Hi,

Thank you very much for replying. I am using a shared server and the server is saying me that they can not change from their end.
I have set the admin settings to my local time zone +05.30 GMT and the users deafult time is also that. I am checking all new user registrations and their profiles and I can see it has set it properly. But the forum is using something else and I think it is the server's time.

I did users and admin settings to the different time zones and it was still same.

I am using 5.2.4 AF.

Please can I know where have I done this wrong? Appreciate your advises.

Can I change this in SQL or in the code? If yes, I'll give a try as this is such imortant in a forum.

Thank You!

**Comment by supermansrf** [comment]
What version of dnn are you using?

**Comment by maduranga001** [comment]
DNN Version:
07.03.04 (45)

Thanks!

**Comment by supermansrf** [comment]
Also do you have any other modules on the site you can check and see if the time is right for that? Like a blog module or something else?

What about if you change a module somewhere like an html module. If you look back in the version history does the edit time match what actual time you set? 

As long as the time is correct on the server and it should be (doesn't matter what time zone it's in or set to) but as long as the base time on the website is correct AF should show posts based on user time. I'm guessing that there is something else wrong. The site/portal time will really only effect logs and other admin functions. It's the user time zone that adjusts the posts to show them on the correct time for each user. I have several forums with users world wide and they all function properly. 

This is what leads me to believe it may be something else. Can't say for sure though.

**Comment by supermansrf** [comment]
What about your dnn even logs? Does the time show properly in there?

**Comment by maduranga001** [comment]
Hi,

Thank you again for your reply.
I am using Ventrian Shoutbox module in the site and that is too old too. That is using also this wrong time.
Yes the log also seems having that wrong timing.
But where have I missed then? I have done the the changes in the admin settings and also I checked my user account too. and other accounts as well. All have set to +05.30 GMT. Can't I handle this in the module? 

Please can you advise me where do I need to check this as an experienced with DNN? 

Thank You!

**Comment by ChrisHammond** [comment]
Start checking the Portal Time zone setting, and then check your user profile time zone setting.

**Comment by maduranga001** [comment]
Hi Chris,

Thank you very much for your reply and helping me.

I checked  above both admin settings and also each users profile settings. It has the values as I want +05.30 GMT set and still time is giving a wrong one. It is about 10 hours different i think. May be the American/Canada time.

Thank You!

**Comment by ChrisHammond** [comment]
What is the time on your Server itself, in Windows, both on the web server, and the database server

**Comment by supermansrf** [comment]
If its off by 10 hours, are you sure its set to +5.30 and not -5.30?  That would be the only way I could see if being off by 10 hours.  If it was set to GMT it should be of by 5.5 not 10.  

Double check Admin > Site settings > advanced settings > usability settings > site time zone and make sure its set to UTC +5.30

@ChrisHammond it sounds like he doesn't have access to windows. Shared host so plesk portal maybe or something similar?  I'm unfamiliar with this.

**Comment by supermansrf** [comment]
Actually I'm wrong, it that was the case it would be off by 11 hours not 10.  I don't understand the 10 hour difference

**Comment by maduranga001** [comment]
Hi Chris.

I double checked it is +05.30 Sri Jyawardhanepura. That is what I want.

My time is 1.30 AM now and the wrong time display in the site is 12.00 Noon now.

I am using Shared window.

Thank You!

**Comment by ChrisHammond** [comment]
Gotcha, if it is a shared environment, the Portal time zone needs to be set to whatever the server time is, and then the profiles need to be set to the user's time.

Perhaps that's already been stated, I'm late to the conversation and too lazy to catch up :D

**Comment by maduranga001** [comment]
You mean I should set the portal time settings to the same as the server time zone and then users need to set their time to the time zone in my country?

I wanted to give the default zone as my time zone as they dont have much idea or they wont set up this time zone unless only if they want to change this. 90% users are in my country. If I change the portal settings, that wold display that time zone. Anyway I did change the admin settings too for different time zones and it was also same result. 

Thank You!

**Comment by maduranga001** [comment]
Can i change this with the web.config?

This is what I have currently.
    <globalization culture="en-US" uiCulture="en" requestEncoding="UTF-8" responseEncoding="UTF-8" fileEncoding="UTF-8" />

But I do not think this will affect to this time zome settings. Not sure why it is not taking from my portal time settings at all.

Thank You!

**Comment by maduranga001** [comment]
Hello,

I upgraded the site to AF 6.1.3 module to the latest.
Also upgraded to the DNN 7.4.0 to the latest to the date.

But still my time zone issue is there only for this module. I changes all values. But the posted date and time is not my time zone. My user account (and most of others) has +05.30GMT and the admin settings zone too.

But it is giving the US time.(The server is in US I think. Using Arvixe shared hosting) Please can you help me? I need user's profile's selcted time zone to be there.

Sebastian Leupold from the DNN team adviced me this is the module related issue. Other modules hasn't this problem.

Please help me. This is very important to a social forum site.

Thank You!

**Comment by supermansrf** [comment]
So I just tested this on one of my sites.  I have a non-admin user created for myself.  I am in the Eastern time zone (-5 GMT).  I posted something at 2:17 PM eastern time on 2/16/2015.  I viewed it from my user who was in the -5 GMT zone.  I saw 2:17 PM.  I changed this user to +5:30 Sri Jyawardhanepura, refreshed the page and I see the post one day later at 1:17 AM 2/17/2015.  This is a change of 11 hours.  Now it appears to not have read the :30 because I would expect it to be off by 10.5 hours instead of 11 but I would assume that this has more to do with DNN than AF.  

The point I'm trying to make here is that AF is reading the time zone change from DNN.  Where that zone list is and what it does I have no clue because I don't know anything about it.  Sebastian Leupold definitely knows what he is doing.  I'm not making any claims against his expertise.  God knows he's far more advanced than I am.  My point is that I don't know that he was given enough information to accurately make a claim against AF for being the culprit.  And does he know the statement that you made about your event logs and Shoutbox not showing the proper time?  

All AF is doing is factoring in the user's time zone when showing you the time a post was made.  All posts are made at the same exact time for each of us.  How we interpret it is up to your time zone.  I know that AF keeps an accurate listing of posts because I have never seen this before.  If it is incorrectly showing you the time because of something else.  

You yourself said that your event logs are wrong, as well as another module on the website is showing time wrong.  There has to be something that you are missing.  

As far as setting the time.  I have a dedicated server, so i have no clue how arvixe controls things.  But my server is set to eastern, I have my sites all configured for eastern time zone (-5).  All this should do is put them on the same page as far as what an admin or host account sees in things like the event logs.  If you were to log on, with a zone of +5:30 you should see the event logs with the proper time for your area.  As well as posts on the forum.  

So I have another question.  Are you looking at the forum itself or relying on email notifications?  I have noticed that sometimes email notifications times don't match the post time.  

If I were you, I would focus only on making the site show you the correct time first.  Login and then check event logs and see if your login was showing up at the right time.  If not you need to fix that first.  Then worry about the forum.  

I have a friend in Delhi who I believe is in the same time zone as you.  He works on one of my sites quite frequently.  I will ask him to create an account and look at my posts and see what happens.

**Comment by supermansrf** [comment]
I have asked my developer to look at this for you.  I'm going to have him investigate my site working with his time zone +5:30 to see if its an AF issue or configuration issue.  It may be later this week, weekend or next week but he will get back to me and either post here or I will relay his notes.

**Comment by maduranga001** [comment]
Hi,

Thank You very much for the reply. And also for your special effort to find this out problem.

Sebastian Said the event viewer should give the server's time as it is working wioth the server. So the Event viewer is working like that anf giving the server time for event log.
The Ventrian shoutbox module was an outdated one and has not updated for years. I removed it and using another module now. So that issues has not in other modules.
I am using DNNChat module too in this site. It is giving the time for the user properly.

I contacted the server support and they said my server is located at HongKong and but it is using and set it up for UTC-08:00) Pacific Time (US & Canada) time zone.

As per your above instructions, I changed the time zone in "Usability Settings" in the site settings to "UTC-08:00) Pacific Time (US & Canada)"

Then user account of mine (not the host/admin account. I have a seperate user account as a normal user in the site.) chnaged to +05.30 GMT Sri Jayawardhanapura.

Results
1) When I open a forum post, then the time is ahead by 30 mins. I think this is what you explained above and you mentioned this. If I could have to change the Site Settings to -07.30 GMT this would work., But there's no such a time zone. So stil this is wrong. But 30mins now.
I changed user time settings to +05.00 and +06.00 too. But it is not a good soluons and also did nto give the correct time to match to my current time.

2) I am using the What'sNew sub module too. That has the server time. Not only 30mins.
I am using your predefined token for this. ([DATE]	- Displays the date when the post was created.)
Is there's a way to get the post/comment posted date for the user prefered time zone?

3) There's not an available option to load last created/posted  Topics/comments in the home page. This is a forum site and the whole website is based on the forum module and it's data.
I am loading last comments and the details using an SQL reporter module. Created an SQL view in the database and loading the info to that module. I can use view's field names as Tokens in this module. So everything is based on the SQL of the database view. But it is alogiving the saved date and time. Not the user prefered time. How can I modify the SQL to get the user prefered time and view that for the comments and posts.

I really appreciate if you can help me for this. The time of the user comments and posts are very important in a forum site.

Thank You!

**Comment by artfuld** [comment]
Spot on @maduranga001 
This is the code in AF
int portalTimeZone = Convert.ToInt32(PortalController.GetCurrentPortalSettings().TimeZone.BaseUtcOffset.TotalHours);
int userTimeZone = Convert.ToInt32(UserInfo.Profile.PreferredTimeZone.BaseUtcOffset.TotalHours);

only taking totalhours as int (without decimals).
Should be fairly simple to change this to use minutes instead, but I'm not sure how many more places it needs to change on.

**Comment by artfuld** [comment]
ok, so it seems like everything was in that line. I'll post a fix for it now.

**Comment by maduranga001** [comment]
Ok. Thank you for this.
Please let us know once you do this modification. Also please tell me which file do I need to move to my website. Only .dll file is enough?

What I can do for the SQL reporting module in the home page? I have to use since we do not have a good Wjhat's new module for now. The time is taking from the database saved post published date and time and that is with the server's time zone. How can I add the user prefered time zone, time difference to that time in the SQL.

It's really Appreciate your support.

Thank You!

**Comment by supermansrf** [comment]
When he fixes the files I will make a new build.

As far as the what's new module. I've said it before. It needs serious
work. This is something I want to work on eventually but it may be
well down the road.

If you have anything to contribute I will gladly include it in future
releases. Until then it's just not a priority.

As you can tell the what's new module hasn't been touched in a long
long time. It needs a lot of work.

I would like to see a lot of what you are asking for working properly.
But I know in my forums there are so many things that are a much
higher priority.

Sorry I'm not more help on this. I don't have any experience with
except the one time I tried using it and promptly deleting it.

**Comment by artfuld** [comment]
@supermansrf it's in there with the other changes I've made.

@maduranga001 as there is more changes in this version you should do the full update and not just change the .dll

**Comment by maduranga001** [comment]
Thank you for the reply. I have done lot of changes to the theme and it's in a separate theme folder.
So I'll upgrade your new version and will use the same theme then. I appreciate if you can advise us if you ad any new styles to the "Default" theme in the future releases. So we can move those styles to my custom theme too.

We are looking forward for the next release and hope we can see an installation version under "stable" tag soon.

Thank You!

**Comment by supermansrf** [comment]
@maduranga001 I finally got @artfuld's pull request merged into this 6.1.4  Will you please confirm if this corrects your issue when you have a moment?

**Comment by maduranga001** [comment]
Hi,

I upgraded the website to new 6.1.4 versoin.

The problem is still same with the time.

Between what should be the time zone in the admin panel? I did change it to different time zones and checked.

But America and Canada has -7.00 or -6.00 
So still the problem is same for +05.30 GMT

Thanks

**Comment by artfuld** [comment]
Strange, when I check on your page the time isn't changed for half hours. But this works on my sites.

I need to take another look at this. Might have something to do with your server being in a half hours timezone.

**Comment by artfuld** [comment]
Hm, something must've gone wrong with your update @maduranga001 
It says on your site that you're using AF6.1.3.0
![6 1 3](https://cloud.githubusercontent.com/assets/6116748/6668062/6637d936-cbf0-11e4-86a7-8ce1c5d0a03d.png)

**Comment by maduranga001** [comment]
Hi,

I installed 6.1.4 version which downloaded from the github.
Do I need to re-install this?

But in the host >> Extention page, It says 6.1.4

Thanks!

**Comment by artfuld** [comment]
Could you redownload and reinstall?

**Comment by maduranga001** [comment]
Downloaded from here and re-installed.
https://github.com/ActiveForums/ActiveForums/releases

Thanks!

**Comment by artfuld** [comment]
And now it looks like it is working.
Please confirm :).

**Comment by maduranga001** [comment]
Confirmed. It is working within the forum module. Thank you very much @artfuld . :)

Please can you give me the same logic to use in my custom module I created to load newly posted comments. This is not a complex module. It's fairly simple. I just used a custom SQL reporter module to load last comments. But the time is giving the posted time. But it is server time.

This is in the home page and users seeing a wrong time. But I know this is not in the AF module issue.
But if you can tell me how to get the UserPrefered time by the SQL, that will be great and i can use the same then. 

Anyway I can see the displaying time is correct now. I changed the Admin settings usability settings "Site Time Zone" to the "UTC -07.00 Mountain Time" too.

Thank You!

**Comment by artfuld** [comment]
This is the code used in AF
int portalTimeZone = Convert.ToInt32(PortalController.GetCurrentPortalSettings().TimeZone.BaseUtcOffset.TotalHours);
int userTimeZone = Convert.ToInt32(UserInfo.Profile.PreferredTimeZone.BaseUtcOffset.TotalHours);

Both PortalController and UserInfo is part of the DNN framework and should be accessible inside any module.

**Comment by maduranga001** [comment]
This is C#.. right? 
Anyway I am using only an SQL statement to load the data and displaying the recordset data in tokens.
That is how SQL reporter module works.

Thank you for your advises.

**Comment by artfuld** [comment]
Yes that is C#.
Only thing you would need is the users offset to the server and then set that offset on the time they got from the db. Perhaps you could even do this directly in the sql-query, or create a stored procedure.

**Comment by maduranga001** [comment]
Honestly, We are looking for a good "What's New" Module and I know this is in your mind. Looking forward this.

I am using that custom module for that to load the latest comments until we have a proper What's new module.
(The current What's New module is not working as we want. : )

Thanks!

**Comment by artfuld** [comment]
@maduranga001 could we close this thread and mark it as complete?

Fixing the whats new module is a pretty big thing and probably needs its own thread :).

**Comment by maduranga001** [comment]
Hi @artfuld 

The timezone issue is fine now. It is working within the forum. Just finding to get it just within an SQL.
But you helped and fixed this issue in the module. So yes you can close it. You are great. Fixed this issue for us.

These three issues are mentioning the same feature that we are lokking for a what's new module. :)
https://github.com/ActiveForums/ActiveForums/issues/217
https://github.com/ActiveForums/ActiveForums/issues/218
https://github.com/ActiveForums/ActiveForums/issues/225
So not opening a new one.

Thank you for the great help.
