### ISSUE TITLE
Top Posters

### ISSUE THREAD

**Issue by maduranga001** [ActiveForums/ActiveForums#224]
I need to get the top 10 posters (total num. of points) as a list with the number of total posts,prifile pic and the username. Please can you help me to get the SQL for this? Or do we have a inbuild solutions?

Appreciate your help.

Thank You!
##

**Comment by johnhenley** [comment]
Not the prettiest solution, but I use the DNN Reports module with this query, and display the top 10 posters with a link to their profile page (note that the tabid for the profile page is hard-coded!):
select distinct top 10
'<a href="/MyProfile/tabid/502/UserId/'+LTrim(RTrim(Str(Users.UserID)))+'/Default.aspx"  title="View '+Users.DisplayName+'''s Profile">'+Users.DisplayName+'</a>' as Name
, (activeforums_UserProfiles.TopicCount + activeforums_UserProfiles.ReplyCount) as Posts from activeforums_UserProfiles
INNER JOIN Users
on Users.UserId = activeforums_UserProfiles.UserId
INNER JOIN UserPortals
on UserPortals.UserId = Users.UserId
and UserPortals.PortalId = 0
where activeforums_UserProfiles.UserId <> 10 -- excludes my posts
and Users.isDeleted=0
and Users.IsSuperUser=0
and UserPortals.isDeleted=0
and UserPortals.Authorised <> 0
order by  (activeforums_UserProfiles.TopicCount + activeforums_UserProfiles.ReplyCount) desc


John

**Comment by maduranga001** [comment]
This is fine and I can load it in a report module with a template driven option. Thank you very very much!

**Comment by ericktj** [comment]
Great Work, Thanks
