### ISSUE TITLE
Split button breaks when post is locked

### ISSUE THREAD

**Issue by supermansrf** [ActiveForums/ActiveForums#227]
Just making a note so i don't forget.  I just locked a post with a decent number of replies.  Once the post is locked, the Split button disappears and turns into [SPLITBUTTONS] 

Not sure how this should behave after locking, I would think that removing some of the content would be ok but mainly want to document this for future use

**Comment by artfuld** [comment]
So the logic for the splitbutton was inside an if-block that checked if the quick reply should be visible. I have made a change for this and done a pull request.

**Comment by artfuld** [comment]
@supermansrf can we close this issue?

**Comment by supermansrf** [comment]
Issue fixed in 6.1.5
