### ISSUE TITLE
Create Forum Administrator role

### ISSUE THREAD

**Issue by Jothay** [ActiveForums/ActiveForums#232]
I would like to have an account that is *not* a super user (like host is) that can access the control panel for the forums, how do I do that?

**Comment by supermansrf** [comment]
All you need to do this is add the administrator role to the user.  Granted it will add all administrator functions to the portal, but it will not be a host (super user) account for the entire DNN install.  

Was this what you were looking for?

**Comment by Jothay** [comment]
I don't want the account to see the DNN Admin menu bar, just the Active Forums control panel

**Comment by supermansrf** [comment]
If you add a role to the module edit permission then add the user to that role, they will get the control panel for the forum and no DNN admin functions.  

I just tested this, this is exactly what I did:

Create new role 0Test Forum Admin
Assign user to 0Test Forum Admin role
Go to AF module settings > permissions > add role 0Test Forum Admin to permissions and assign Edit permission 

Log in with test user and user has control panel and no other permissions.

**Comment by Jothay** [comment]
Perfect! That did exactly what I needed.
