### ISSUE TITLE
Extension gives an error

### ISSUE THREAD

**Issue by shwetathakar** [ActiveForums/ActiveForums#234]
Hi,
I am using Active Forum 5.2.2. When I tried to upload source code version from Github it gives me an error like: couldn't find License.txt. I am not able to upload this extension. Please help me to resolve this.
Should I require any license for that?
##

**Comment by supermansrf** [comment]
You can't directly install the source into dnn. You have to either download the installer or setup a dev environment with the source

**Comment by shwetathakar** [comment]
Thanks for reply. But as per guideline  I am installing zip file from HOST ->extension-> Available extension tab. Can you please explain me with more details?
 Thanks.

**Comment by supermansrf** [comment]
I apologize for not responding. I know this is a bit old but somehow I missed your reply.  When you go to releases on here (github) there are a few options that you can download.  What you want to download is the activeforums_06.01.03_install.zip  you can not install the source code via host > extensions.  To install the source code you have to setup a dev environment.  If you do grab the file I listed above, you can install that via host > extensions

**Comment by artfuld** [comment]
@shwetathakar did you get this fixed?
