### ISSUE TITLE
Couple of issues with AF

### ISSUE THREAD

**Issue by Arkix** [ActiveForums/ActiveForums#235]
Hello, i have a couple issues with the Active Forum module.

First, when i select the option for moderate comment and the  user send a comment later than make click in send comment the page charge with a error message, if i unselect the option of moderate comment in the dashboard, the user can make comments without problem.

The other issue is when i cite a comment of the other user the cited comment apperas with the html markups "<span>comment</span>" (something like that).

Please help me to fix that issues. thank you.
##

**Comment by supermansrf** [comment]
This is probably something that has been overlooked for a while.  There are several features within AF that haven't worked properly in a while.  Features that aren't really popular just haven't gotten the attention the deserve.  I'm guessing this is one of them.  I personally don't use this feature so I can't tell you how its supposed to work or why it doesn't.  Maybe someone can take a look at it.

**Comment by artfuld** [comment]
Hey @Arkix i tried both moderation and quotes but I didn't get an error.

Can you please tell what version of AF and DNN you're using.
