### ISSUE TITLE
Update on State of Active Forums

### ISSUE THREAD

**Issue by supermansrf** [ActiveForums/ActiveForums#237]
I know that things have been a bit quiet lately.  It doesn't mean that things aren't being done, I've just been extremely busy.  I haven't had the time to do anything but I have been planning and coordinating things behind the scenes.  

Hopefully, within the next 3-4 weeks, I will be able to officially say that the new UI/UX is complete.  I have been in discussions with a team of developers to finally get this knocked out and I am very excited about this.  One major change that I have asked to be implemented is the ability to have a more responsive layout when in topic view.  This has been a huge problem for all of my websites.  I have many profile properties and customizations around the avatar and author area and they take up a large amount of real estate.  What I have asked is for the author "block" to stay where it currently is for desktop and tablet view, but when switching to the mobile view, the author block will move to above the post/reply to allow the full width of the device for each area.  

We will also be finishing up with the implementation of new icons, clean things up, and get this completely wrapped up.  Also since there will be a team dedicated to doing this, future changes will hopefully be a lot quicker.  These guys will learn a lot during their adventure and I have every intention of using them more in the future.  They have already been doing several upgrades/repairs of AF in the past few months so its not completely new to them. 

The next plan after the UI is done is to move forward with the new tapatalk integration.  I personally have been really struggling with tapatalk.  It has become a major disaster on several of my sites.  At times it will even shut off the application in IIS, sometimes many times per day.  This is obviously not the best thing if you aren't around to restart the application the site is dead until restart.  Its frustrating.  The best course of action is to just start over again with this and work towards updating everything.  As I have said before, I have been in discussions with tapatalk directly about this.  They have started creating a new .net version of the plugin and are willing to incorporate it into the forum.  They have their software built into several forums natively and it appears to be working well for them.  I don't see any reason not to do the same with AF.  Its really quite simple, if you don't want it, don't turn it on.  If you do its already there, no installing a separate module, no keeping a separate module up to date.  I don't feel that it would ever hold back the development of AF because the current plugin is very old and outdated, so if we would see compatibility issues we should now.  It could be argued that I do see compatibility issues now that affect AF (I mentioned one big one above) but as soon as I disable the tapatalk handler the issue immediately goes away.  So same with the new version.  If a problem comes up that shuts down the forum, just turn it off.  I don't see this happening because since things will be done more conventional than they are currently, keeping things up to date and current should be much easier.  

So there it is in a nutshell.  Any questions, comments, concerns feel free to reach out.  I hope to push out a new 6.1.4 update in the next day or 2 with a few small pull requests.  I will obviously keep everyone updated as I am able to get things accomplished.  Thanks!
##

**Comment by artfuld** [comment]
Gj @supermansrf !

**Comment by artfuld** [comment]
If you have the time it would be really nice if you could clean up among the Issues. A lot of them has been fixed but aren't closed and for someone that wants to help it's hard to get a quick overview of what issues needs attention.

**Comment by supermansrf** [comment]
@artfuld would this be something you would be interested in doing if I assigned you permissions?

**Comment by artfuld** [comment]
I can try atleast! :)

**Comment by supermansrf** [comment]
you should have access to do so now.  There may be other permissions assigned by me adding you.  I'm curious to know what these are.  The organization permissions of git are not that granular.  If what I added doesn't work let me know and i'll try something else.  Just sent you an invite.  Thank you!  This will really help

**Comment by teambound** [comment]
Thanks for your efforts! I have not attempted to upgrade yet since the groupid issue but it appears that group issues have been fixed. Is this right? I was hoping that the AF demo site could be setup with a group and the latest version so I can see if everything works ok. I don't have a test site... bad I know.

Also great to hear about tapatalk. One thing I hope is considered with tapatalk is the ability to use it with multiple forums instances. I have 2 instances of AF on my site but can only point tapatalk to one of them.  Of course I may be doing something wrong. Also, it would be important for group forums that the groupid/role is respected so  when viewing forums on tapatalk I wont see forums I don't have permissions to see. Maybe it already does this.

In any event thanks again and please let me know if the groupid and subforum issues within groups is fixed. Is anyone using it in group mode?

**Comment by supermansrf** [comment]
I have a test site setup for active forums.  If you would like, I can update activeforums.org to 6.1.4 ( I'm having a problem upgrading DNN past 7.2.2 for some unknown reason).  But I can let you have at it and do your thing.  It will be a disposable site so you can set it up however you want and then we can have others look at it.  

You still have my email address?

**Comment by supermansrf** [comment]
Correction, I can update activeforums.org to 6.1.4 and then clone it again to the test site for you to work with.

**Comment by teambound** [comment]
I believe I do have your email address. Just sent an email. A test site would be great then I could give it a through test.

Thanks.

**Comment by artfuld** [comment]
@teambound i will go over all the posts that you've posted about groups and see if there's anything I can do. Not making any promises other than I will have a look at it.

**Comment by teambound** [comment]
Appreciate it. AF for groups is real important for my site and it would be great to upgrade to the latest version.

Thanks

**Comment by artfuld** [comment]
@teambound most of the posts that I find is regarding the groupId being lost. And from what I understand @peppertree has made changes for that to work.
I also tried it locally and it works for me.

**Comment by maduranga001** [comment]
I was also looking for the new version release. Please can you tell me if you addresses this issue which I mentioned in this thread. (https://github.com/ActiveForums/ActiveForums/issues/226)

<img src="http://i58.tinypic.com/b8lo43.jpg" border="0" alt="" />

This is the most important issues at this time. I can not merge or split.

Please advise and help. which files do I need to check?

**Comment by maduranga001** [comment]
You have mentioned that in new 6.1.4 version has updated 6.1.3's sqlprovider file with missing {objectqulifier} in line 105

But I found about 10 places that has missed {objectqualifier}. I modified this manully and rerun the script.

I attached it with this.
Please can you check this and find still if you have miossed this?

I belived there should be more too. But not sure.

This is the file which I modified.
<a href=http://www.filedropper.com/060103><img src=http://www.filedropper.com/download_button.png width=127 height=145 border=0/></a><br /><div style=font-size:9px;font-family:Arial, Helvetica, sans-serif;width:127px;font-color:#44a854;> <a href=http://www.filedropper.com >file upload storage</a></div>

Thank You!

**Comment by artfuld** [comment]
gj @maduranga001 
Just did a recheck of that file and you're correct. it was missing a couple of objectqualifiers.

That should not affect the split button unfortunately in your case :).

**Comment by maduranga001** [comment]
Hi artfuld,

Thank you for checking it.
I just want to know still if I have missed {objectqulifier} in the SQL scripts which is related to the split/merge option.
Between are you modifying 6.1.4 sqlprovider file with the missing {objectqualifier} which I've added? Otherwise I'll missing those again with 6.1.4 installation.

If this is not a case with the SQLscript or with the files you modified, then where is the issue?

What are the details that I can provide you? I can send you any. I just want to fix this.

Did you get that error (the screenshot in the previous message) in the previous versions?
I saw you mentioned that you have fixed a simillar issue that in 6.1.3 version release note.

If you have done any changes, in which files in the modules? I can check those files then.

Please help me. I am struggling with this problem as this is one of important feature in our social forum website.

Thank You!

**Comment by artfuld** [comment]
The sql for the splitfunction is in 5.1.3 and it has all the objectqualifiers needed
