### ISSUE TITLE
CKEditor and 6.1.4

### ISSUE THREAD

**Issue by TBGoat** [ActiveForums/ActiveForums#242]
I've installed 6.1.4 on my new site and want to change the forms to use CKEditor.  It doesn't seem to be an option.  My two choices are Default and TopicEditor, but both look the same when I try them. Is there something in the configuration I'm missing?

**Comment by supermansrf** [comment]
The settings in control panel don't always stick.  I use a script to do this. Each time I change a setting in control panel I run this script. I typically do it in SQL Management Studio

SELECT * from activeforums_Settings 

WHERE (SettingName = 'EDITORTYPE') 

GO 

will find out current settings so you can save them if you want.  




UPDATE activeforums_Settings 

SET 

  SettingValue =  '2'

WHERE (SettingName = 'EDITORTYPE') 

GO 

Will change to default dnn editor

**Comment by artfuld** [comment]
you need to go in to the settings for the specific forum and set HTML input for that specific forum.
![image](https://cloud.githubusercontent.com/assets/6116748/6697461/e882af64-ccf0-11e4-865c-8fdbb63c3ffb.png)

**Comment by TBGoat** [comment]
Thank you so much!
