### ISSUE TITLE
Release 6.1.5

### ISSUE THREAD

**Issue by supermansrf** [ActiveForums/ActiveForums#243]
I have removed the installer from 6.1.4 and released 6.1.5.  I would recommend anyone who installed 6.1.4 to upgrade to 6.1.5

Also note that on every site I have installed 6.1.5 on, in order to see the build change in control panel, I had to install twice.  The repair install seems to have fixed the build number.  

Additionally, one site still showed 5.2.4 before doing the repair even though it was already on 6.1.3 so this isn't a new issue.  I suspect the control panel having a bug of some sort.

**Comment by artfuld** [comment]
Had some problem with this install.
First install, the version in control panel still said 6.1.0 (yes I'm a slow updater)
Second install (repair) the forum stopped working.

I have rolled back now and will check tomorrow why it broke.

**Comment by ChrisHammond** [comment]
I upgraded from 5.2.0 to 6.1.5 today in production. So far so good.

**Comment by artfuld** [comment]
@ChrisHammond do you get the correct version number in the control panel?

**Comment by artfuld** [comment]
Somehow the 5.2.4 sql-script hadn't been run on my installation and that's why my forum stopped working.

Everything works fine now!

**Comment by artfuld** [comment]
I had another issue, don't know if it is at all related to any update (it shouldn't be), but I'm writing it here in case anyone else have the same problem.
When I tried to post a new post (quickreply still worked) it gave me an error saying
"Message:'true' cannot be parsed as a unit as there are no numeric values in it. Examples of valid unit strings are '1px' and '.5in'."

For some reason the setting for editorwidth was set to "true" and only for one forum. Just changed it to 100% fixed the problem.

**Comment by supermansrf** [comment]
Issues corrected in later builds
