### ISSUE TITLE
Not receiving email notifications

### ISSUE THREAD

**Issue by uba-tech** [ActiveForums/ActiveForums#244]
I am testing with the current installment (6.1.5) and I am not receiving any notifications when I create a new topic or reply to an existing one. I checked the database and the Queue table is not populating. I enabled the Mail Queue in the module settings but that didn't fix my issue. Am I missing a step somewhere? Please advise.

Thanks!

**Comment by supermansrf** [comment]
I personally have never tried message queue.  Have you tried turning it off?  I have several fairly active forums.  Some send out 5k-10k notification emails per day.  I have never used the queue and its always worked.  

Try turning it off and see what happens.

**Comment by uba-tech** [comment]
It's off by default. I turned it back off after testing but neither way seems to work.

**Comment by supermansrf** [comment]
So I just want to make sure you are doing the right test.  But I've found that if I'm subscribed to a topic and I reply to the topic (same user) I will not get notification.  Also my host account never receives notifications. An administrator account will but not a host account for some reason.  I believe it has to do with email address visibility permissions but just a guess.  

Make sure you test with more than one regular user and not your host account.  This is one thing I have never had an issue with on my sites (after the fix for DNN 7.2.2 I believe).

**Comment by artfuld** [comment]
Just got the upgrade for 6.1.5 and the email notifications work fine for me.

@uba-tech did it work earlier in the forum? What version did you upgrade from?

I'm certain that no one has touched the mailing part of the forum for a very long time so it should work as it always has.

**Comment by ManagedTech** [comment]
Hello Artful,

Currently I am getting the following errors when I attempt to send notifications:
Message:Must specify valid information for parsing in the string.
StackTrace:
InnerMessage:Must specify valid information for parsing in the string.
InnerStackTrace:
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at DotNetNuke.Modules.Announcements.Announcements.get_viewType()
   at DotNetNuke.Modules.Announcements.Announcements.BindData()
   at DotNetNuke.Modules.Announcements.Announcements.OnLoad(EventArgs e)

and 

Message:Failure sending mail.
StackTrace:
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   at DotNetNuke.Modules.ActiveForums.Email.SendNotification(String FromEmail, String ToEmail, String Subject, String BodyText, String BodyHTML, Int32 ForumID, Int32 TopicId, Int32 ReplyId)
InnerMessage:Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.
InnerStackTrace:
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.PooledStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.Mail.SmtpPooledStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at System.IO.Stream.Dispose()
   at System.Net.ConnectionPool.Destroy(PooledStream pooledStream)
   at System.Net.ConnectionPool.PutConnection(PooledStream pooledStream, Object owningObject, Int32 creationTimeout, Boolean canReuse)
   at System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)
   at System.Net.Mail.SmtpTransport.GetConnection(ServicePoint servicePoint)
   at System.Net.Mail.SmtpClient.GetConnection()
   at System.Net.Mail.SmtpClient.Send(MailMessage message)

I had re-set my SMTP settings, and it sent out for a short period, and then stopped.  After that, these errors showed.

**Comment by artfuld** [comment]
I'm not an expert on general dnn-stuffs but it looks to me like something has happened to the mail feature.
Is there any other module that still can send emails when this happens?
"An existing connection was forcibly closed by the remote host." this points to something being wrong at your email hosts end. Perhaps you're only allowed to send xx emails per day or something?

**Comment by ManagedTech** [comment]
SMTP tests work without problems, so the mail function of the DNN installation seems to be fine.

**Comment by artfuld** [comment]
The first error that you write comes from the module Announcements and shouldn't have anything to do with AF.
Can you try to send a newsletter to yourself just to see if it actually works? The smtp test logs into the mail account it doesn't actually try to send something (correct me if I'm wrong). So the problem could still be that you're only allowed to send xx emails per day via smtp.

**Comment by ManagedTech** [comment]
When I test SMTP, a mail is sent successfully to the admin's email account and i can read it.

However, each time I make a post in the active forums, the error about valid information being provided to the announcements module is thrown. 

This is the only time this error is thrown. The site version is 7.4.0, and the module version is 5.2.2

**Comment by artfuld** [comment]
@ManagedTech I stand corrected then about the mail test :).

5.2.2 is to early for me to say what has been done and what not. I suggest you upgrade to the latest version of AF unless there's some specific reason to keep the old version. But then I recommend that you don't update DNN either.

**Comment by ManagedTech** [comment]
@artfuld 

Thank you for responding so quickly. I had a look around for the active forums module, but the codeplex link gives me version 5.2:

https://activeforums.codeplex.com/releases/view/119625

Is there somewhere else I should be getting this?

**Comment by artfuld** [comment]
https://github.com/ActiveForums/ActiveForums/releases right here on github :).
Since you're upgrading you will need to run the 
5.2.2 sql-script after upgrade and maybe also 5.2.4
