### ISSUE TITLE
Subforum title displays

### ISSUE THREAD

**Issue by TBGoat** [ActiveForums/ActiveForums#245]
Has anyone written templates to make subforums display in a manner that makes it instantly obvious they are subforums?

The default forum display makes them look as though they were simply another forum.

**Comment by supermansrf** [comment]
I have a team working right now on finishing up the UI changes introduced in 6.  There are many things that never got finished.  Hopefully within a few weeks this will be done.  We can look at what you are talking about once I see the new UI.  

AF doesn't support sub-forums.  Only groups and nested forums under the groups. Is that what you are talking about?  If you give me some ideas I will gladly take them to this team and try to get them incorporated into this new UI change.

**Comment by TBGoat** [comment]
In our site, we have a high level group which is basically just "groups", beneath that there are forums  and within each of those forums there are subgroups that need subforums of their own. 

If groups could be nested within groups, that would work, as well.  Here's an example of what I'm talking about from another forum:

![image](https://cloud.githubusercontent.com/assets/11527822/6716356/2a797724-cd62-11e4-85b9-938ee82ebcc7.png)

**Comment by supermansrf** [comment]
What version of Active Forums are you running?

**Comment by TBGoat** [comment]
I've installed 6.1.4.

**Comment by artfuld** [comment]
@TBGoat I'm far from a front end developer but I made this in 15 minutes.
![image](https://cloud.githubusercontent.com/assets/6116748/6718423/e6392706-cdb3-11e4-9992-8609b3e338b2.png)

it's really easy to change, the first thing I do when trying out new templates I take away all the css and just go from there.

**Comment by TBGoat** [comment]
That's absolutely perfect, @artfuld.  Would you consider sharing the code you wrote? I'm a database dev. Front ends confound me (though I'm suddenly learning pretty quickly out of necessity).

**Comment by artfuld** [comment]
<%@ Register TagPrefix="af" Assembly="DotNetNuke.Modules.ActiveForums" Namespace="DotNetNuke.Modules.ActiveForums.Controls"%>
[BREADCRUMB]
[GROUPSECTION]
<style type="text/css">
	.bgBla {
		background-color: rgba(0, 0, 255, 0.3);
	}
	.icon {
		width: 34px;
	}
	.width60 {
		width: 60px;
	}
	.LastPost {
		width: 120px;
		font-size: 10px;
	}
	Table {
		cellspacing: 0;
		cellpadding: 0;
		width: 100%;
	}
	.subforums {
		font-size: 12px;
		cellpadding-left: 15px;
	}
	.iconSubForum {
		width: 20px;
	}
        .subForum img {
            width: 10px;
        }
</style>
<div>
	[GROUPNAME]
	[GROUPCOLLAPSE]
</div>
[GROUP]
	<table>
		<tr class="bgBla">
			<td colspan=2>
				<div>[TRESX:FORUMHEADER]</div>
			</td>
			<td>
				<div>[TRESX:TOPICSHEADER]</div>
			</td>
			<td>
				<div>[TRESX:REPLIESHEADER]</div>
			</td>
			<td>
				<div>[TRESX:LASTPOSTHEADER]</div>
			</td>
		</tr>
		
			
		[FORUMS]
		<tr>
			<td class="icon">[FORUMICON]</td>
			<td>[FORUMNAME] <br />
		[SUBFORUMS]<span class="subForum">[FORUMICON] [FORUMNAME]</span>
		[/SUBFORUMS]
</td>
			<td class="width60">[TOTALTOPICS]</td>
			<td class="width60">[TOTALREPLIES]</td>
			<td class="LastPost"><div>[LASTPOSTSUBJECT:25]<br />[TRESX:BY] [DISPLAYNAME]<br />[LASTPOSTDATE]</div></td>
			</td>
		</tr>
		[/FORUMS]
	</table>		
[/GROUP]
[/GROUPSECTION]

[WHOSONLINE]
<div style="text-align:right;">[JUMPTO]</div>

**Comment by supermansrf** [comment]
@artfuld you amaze me.  I was told AF only supported single level nesting (forums under group).  Is this not true?  

I've had some issues in the past just sorting the groups and forums.  It seems that somehow gaps will appear in the sort order in the database making things be off by a number or two.  I've had to manually sort things in the database directly to get it to work right again.  Maybe we can get this to work right and allow better nesting (multiple groups etc).  

Can you just convert to a txt file and drop it on a reply?

**Comment by artfuld** [comment]
I think two levels have been working for a rather long time. Not sure what you mean :/.
Not allowed to post .txt here as files :/ only images.

**Comment by artfuld** [comment]
Group1
 - Forum1
 - - SubForum1

Theese are the levels supported.

**Comment by TBGoat** [comment]
Thanks, @artfuld .  Please send to databaseartisinary@gmail.com .

**Comment by artfuld** [comment]
Glad I could help!
