### ISSUE TITLE
My Settings -> 404

### ISSUE THREAD

**Issue by johnhenley** [ActiveForums/ActiveForums#249]
When i click on the 'My Settings' toolbar link in the regular (non-group) forums page (http://localhost/forums.aspx), I get a 404 for this page/URL:
http://localhost/forums/views/afprofile/

**Comment by artfuld** [comment]
Do you have some sort of url-rewriter installed?

**Comment by johnhenley** [comment]
I have these two:
DotNetNuke.Modules.ActiveForums.ForumsReWriter, DotNetNuke.Modules.ActiveForums
DotNetNuke.HttpModules.UrlRewriteModule, DotNetNuke.HttpModule

If I remove this one:
DotNetNuke.Modules.ActiveForums.ForumsReWriter, DotNetNuke.Modules.ActiveForums
I get same 404 error.

John

**Comment by artfuld** [comment]
Just enabled the active forums url handler and I recieve the same problem.
Will try to get a fix for this during the day.

**Comment by johnhenley** [comment]
Thanks for your help!
John

**Comment by artfuld** [comment]
@johnhenley I have a quickfix for this ready for the next release.
