### ISSUE TITLE
Is there a script to import data from one forum portal to another?

### ISSUE THREAD

**Issue by TBGoat** [ActiveForums/ActiveForums#251]
I'm looking to move my forum from one portal to another and am wondering if anyone has already written a script or documented the steps required?   (If not, I probably will)

**Comment by TBGoat** [comment]
This seems to do it (obviously, replace your own module IDs):


DECLARE @OldModuleID INT ,
    @NewModuleID INT;

SET @OldModuleID = 862
SET @NewModuleID = 555

UPDATE  dbo.activeforums_Forums
SET     ModuleId = @NewModuleID
WHERE   ModuleId = @OldModuleID;

UPDATE  dbo.activeforums_Filters
SET     ModuleId = @NewModuleID
WHERE   ModuleId = @OldModuleID;

UPDATE  dbo.activeforums_Forums_Tracking
SET     ModuleId = @NewModuleID
WHERE   ModuleId = @OldModuleID;

UPDATE  dbo.activeforums_Groups
SET     ModuleId = @NewModuleID
WHERE   ModuleId = @OldModuleID;


UPDATE  dbo.activeforums_Ranks
SET     ModuleId = @NewModuleID
WHERE   ModuleId = @OldModuleID;

UPDATE  dbo.activeforums_Settings
SET     ModuleId = @NewModuleID
WHERE   ModuleId = @OldModuleID;


UPDATE  dbo.activeforums_Subscriptions
SET     ModuleId = @NewModuleID
WHERE   ModuleId = @OldModuleID;

UPDATE  dbo.activeforums_Tags
SET     ModuleId = @NewModuleID
WHERE   ModuleId = @OldModuleID;

UPDATE  dbo.activeforums_Templates
SET     ModuleId = @NewModuleID
WHERE   ModuleId = @OldModuleID;

UPDATE  dbo.activeforums_Topics_Related
SET     ModuleId = @NewModuleID
WHERE   ModuleId = @OldModuleID;

UPDATE  dbo.activeforums_UserProfiles
SET     ModuleId = @NewModuleID
WHERE   ModuleId = @OldModuleID;

**Comment by artfuld** [comment]
I know that some of the SPs use both PortalId and TabId as parameters, not sure if they're still in use.
But if I where you I would check the tables for thoose 2 and set them aswell, just in case.

**Comment by TBGoat** [comment]
I did research and all the stored procedures that use TabID are using it from the module table or another related table.  None of the TabIds come from the active forums tables.  Portals do, yes.  I was lucky that both my portals were the same ID when I ran it.

The following code will work for anyone in the future:

DECLARE @OldModuleID INT ,
    @NewModuleID INT ,
    @OldPortalID INT ,
    @NewPortalID INT;

SET @OldModuleID = 862;
SET @NewModuleID = 555;

UPDATE  dbo.activeforums_Forums
SET     ModuleId = @NewModuleID ,
        PortalId = @NewPortalID
WHERE   ModuleId = @OldModuleID
        AND PortalId = @OldPortalID;

UPDATE  dbo.activeforums_Filters
SET     ModuleId = @NewModuleID ,
        PortalId = @NewPortalID
WHERE   ModuleId = @OldModuleID
        AND PortalId = @OldPortalID;

UPDATE  dbo.activeforums_Forums_Tracking
SET     ModuleId = @NewModuleID
WHERE   ModuleId = @OldModuleID;

UPDATE  dbo.activeforums_Groups
SET     ModuleId = @NewModuleID
WHERE   ModuleId = @OldModuleID;

UPDATE  dbo.activeforums_Ranks
SET     ModuleId = @NewModuleID ,
        PortalId = @NewPortalID
WHERE   ModuleId = @OldModuleID
        AND PortalId = @OldPortalID;

UPDATE  dbo.activeforums_Settings
SET     ModuleId = @NewModuleID
WHERE   ModuleId = @OldModuleID;

UPDATE  dbo.activeforums_Subscriptions
SET     ModuleId = @NewModuleID ,
        PortalId = @NewPortalID
WHERE   ModuleId = @OldModuleID
        AND PortalId = @OldPortalID;

UPDATE  dbo.activeforums_Tags
SET     ModuleId = @NewModuleID ,
        Portalid = @NewPortalID
WHERE   ModuleId = @OldModuleID
        AND Portalid = @OldPortalID;

UPDATE  dbo.activeforums_Templates
SET     ModuleId = @NewModuleID ,
        PortalId = @NewPortalID
WHERE   ModuleId = @OldModuleID
        AND PortalId = @OldPortalID;

UPDATE  dbo.activeforums_Topics_Related
SET     ModuleId = @NewModuleID ,
        PortalId = @NewPortalID
WHERE   ModuleId = @OldModuleID
        AND PortalId = @OldPortalID;

UPDATE  dbo.activeforums_UserProfiles
SET     ModuleId = @NewModuleID ,
        PortalId = @NewPortalID
WHERE   ModuleId = @OldModuleID
        AND PortalId = @OldPortalID;
