### ISSUE TITLE
unresolved view and read confirmation flag?

### ISSUE THREAD

**Issue by cmsfrotter** [ActiveForums/ActiveForums#253]
First of all: this module is awesome. Why is there no way to donate for this?

I haven't updated to 6.1.5 yet, but use the latest stable marked release, so if this is already implemented, please say so. I know there is a function to view all unanswered or unread threads, but is there a way to show all unresolved threads inside the forum? (if anyone could explain a way how to do that it'd be super special awesome) Already searched the hub and forums, but I didn't stumble across something helpful.

Another thing I'd VERY like to have is a read confirmation feature, especially for important announcements. I guess this second part is more like a feature request, but it would be awesome if you could mark a thread to force read confirmation, maybe only for specific usergroups, and if anyone opens the thread and/or clicks a special button he's added to a list or is removed from the list of people who have to read this topic.

**Comment by artfuld** [comment]
Hello!
The reason why you can't donate for this is simply cause it's an open source module. You can put a bounty on a specific feature so that the person that fixes it gets the money.
But Money doesn't always mean a good product :).

Getting all unresolved issues shouldn't really be an issue. All you need is to get all topics where StatusId == 1. And ofcourse you need to check all the permissions.
Could be a fun thing for someone to do as you could use the sp's for getting unanswered/not read/my... as base for how to get the posts.
I can even give this a try when I get some time.

The read confirmation looks like a nice addon, if you got the time it would be nice if you could write down more specific instructions on how it should work. Should it be able to show one post that needs to be read before you can see all the forums and perhaps even on the forum-level.
Do you want it to be enough that people look at it or should they also need to click some sort of accept-button? Perhaps keep that as an option.

**Comment by cmsfrotter** [comment]
Hello. Wow, that was a fast reply.

I guess that makes sense. And I couldn't agree more. Open source with an active community and a cooperative guy/team behind a product is like the holy grail.

I'm very new to all this, but I'll definitely take a look at the sp. Would it be sufficient to copy&paste the activeforums_UI_UnansweredView sp and just change T.LastReplyID = 0 to T.StatusId = 1 ?
Where would I intergrate that into the site/module? I did a quick fulltext search for the sp name to find the appropriate file, but I guess it's not that simple.

Thanks for your support. A button would be perfect, I'll definitely write some specifics down after the weekend.. or maybe tomorrow.

**Comment by artfuld** [comment]
Yes you can copy the sp af_ui_unansweredView. It should do with the change that you said.
For getting it actually to show in AF you need to use controls/af_grid.ascx

**Comment by cmsfrotter** [comment]
Thank you. I created the sp as described and took a look at the af_grid.ascx. This may be a stupid question but I guess I have to change source and compile it to implement this, don't I? I also took a quick look at the af_grid.ascx.cs source file and I guess I also have to add unresolved to the gview case switch inside that file. I've done programming before, but I'm very new to DNN and didn't mess with any module source before, so this is a first timer. Are there more things I would have to be aware of / to get this implemented? Maybe you have a tutorial or other advice that would help me to get more into the specific matter? I already looked at some sites explaining module programming but that wasn't really helpful, or at least I didn't get the knack of it to get this simple implementation done.

To specify the idea of a read confirmation, what I think about would look like this:
In the topic creation view, there is an option to enable read confirmation for this thread.
When enabled, the thread creator can add single users and/or entire groups to enforce a 'You have to read and confirm this' state for this thread upon selected users/groups.
If a thread with read confirmation exists, users who have yet to confirm they've read a thread can click on a highlighted link (e.g. red color / bold / or to the side of a red exclamation mark icon) like 'Confirmation Pending' or something like that in the controlbar where Unanswered, Unresolved ;), etc. are found.
(Optimally: The status per user should update - as in be added or removed - if a user joins the selected group or is no longer in that group and not selected individually. So if a user joins the moderators group, that user would see a 'all moderators have to read this' topic under the highlighted pending confirmation view and if the user is removed from moderators group after 2 weeks - 'cause he or she did still not read the thread even though there is a highlighted link catching for attention every single day -, that user would not see the pending confirmation anymore after removal, because the read confirmation rule does not apply anymore.)
Inside the thread view, users who have yet to confirm read status have a button to do so, like 'Mark as read' or 'Acknowledged'. I think it's not enough to just open a thread for confirmation, but really confirm that you've read it. An option for just read / buttonclick confirmation would be a good solution if you want both ofc.
Also inside the thread view, the thread creator has a list at the bottom of his 1st post (or maybe a separately 'simulated'/appended post between 1st and 2nd post) where there is a list of all users affected by his previously set 'read confirmation rules', using the name defined as standard display for the forum. Users who already acknowledged the thread have a green check(tick) icon in front or after their name and/or are highlighted green, other users are black/grey/red/default (whatever seems best). This view may be a list or grid, I guess a grid would be better, but could look ugly on mobile(?). Maybe you have a good idea for that display.
I also like your idea of a view restriction on a forum / forum group depending on a read confirmation state, but would not need that personally. However, this would be great for a thread with forum rules or similiar situations, but I guess without a need I can't point out any helpful directions for that one.

That's all I've got so far. If anything is not that clear, please say so and I'll rephrase it / go more into detail. Your thoughts?

**Comment by artfuld** [comment]
Not sure about all the steps so don't take this as a "DO THIS AND ONLY THIS"-list :).

af_grid.ascx.cs
~line 130.

Copy the entire case "unanswered" but change the case to "unresolved"
And change db.UI_UnansweredView(...
to something like db.UI_Unresolved(... *keep the same parameters*.
Rightclick the db.UI_Unresolved and click Generate -> Method stub.
This will create a new method inside common.cs (Components/Data/Common.cs).
Change that method to this.

		public DataSet UI_Unresolved(int portalId, int moduleId, int userId, int rowIndex, int maxRows, string sort, string forumIds)
		{
			return SqlHelper.ExecuteDataset(_connectionString, dbPrefix + "UI_UnresolvedView", portalId, moduleId, userId, rowIndex, maxRows, sort, forumIds);
		}

Where UI_UnresolvedView is what you called your sp in the database.

In utlities.cs (class/utilities.cs) go to Line ~200 and copy the template.replace for unanswered and modify it to unresolved.
            template = template.Replace("[AF:TB:Unresolved]", string.Format("<a href=\"{0}\">[RESX:Unresolved]</a>", ctlUtils.BuildUrl(tabId, moduleId, string.Empty, string.Empty, -1, -1, -1, -1, "unresolved", 1, -1, -1)));

Now to make the link show up change the template toolbar.txt (config/templates/toolbar.txt) 
add
<li>[AF:TB:Unresolved]</li> where you see fit.

And that should be all the steps you need to make. Unless I've missed something.

Wow.. perhaps that was more or less a complete tutorial for this =D. Let me know if you get it to work!

**Comment by artfuld** [comment]
Oh, last thing. In SharedResources.resx (app_LocalResources/SharedResources.resx) add the appropriate resource for RESX:Unresolved

**Comment by cmsfrotter** [comment]
Wow, thank you very much. You are a hero. I already made the changes you mentioned and compiled a release. But since I can't backup the DNN installation / DB right now, I guess the actual test is delayed at least until tomorrow. I'll let you know :)

**Comment by cmsfrotter** [comment]
Finally found time to test out the unresolved view. Works like a charm with your awesome help. Thank you very much

**Comment by cmsfrotter** [comment]
I guess I'll use these steps to implement another view like My Topics named My Resolved to show all threads by the user with resolved status to better use the status on a Q&A basis :)

**Comment by artfuld** [comment]
Good job!

Do you have this under source control so you can release it to the project?

Regarding the read confirmation I think it can be a great addition but it probably would be a rather big project and would need to change much of the core functionality. Perhaps something to think over when the next big release will be.

**Comment by cmsfrotter** [comment]
I saw the manual the other day, still need to read it though. I'll do that when I'm finished and tested everything. Need to edit the latest AF version anyway since I still use 5.2.4. That reminds me: Are there more templates/themes than the default ones for AF6 available anywhere? I guess the old ones can't be integrated -that- well into the new version. At least I get some creepy results when trying :)
Since I added one or two sps I think there's a need to add those to the SqlDataProvider for integration to the project. What's the best practice to do so in this case? Just take the latest one and add the new sps (drop+create) or do that in a new file/version?

Yeah I thought that'd be pretty big. Maybe there is another function we can use as a workaround to at least catch the core function? Maybe there's already a status-like field or something similiar for a user/topic relation we could use?

**Comment by artfuld** [comment]
What I usually do is right click the SP, "Script stored procedure as" -> "Create to" -> "Clipboard".
Then make sure to replace the table names with the correct {databaseOwner} and {objectQualifier}.
Just need to include it in the .sqldataprovider for that version and @supermansrf does the magic.

**Comment by cmsfrotter** [comment]
Mh. I did all changes to the 6.1.5 version and now I'm getting errors when clicking on the control bar links. Compile + install was fine.. Maybe something slipped. Guess I'll try it again from scratch tomorrow :/

**Comment by cmsfrotter** [comment]
Strange. Somehow I even get an error when clicking on any of the control bar filters after successfully compiling and installing the current AF\master branch.

System.Web.HttpCompileException: DNNPATHHERE\DesktopModules\ActiveForums\controls\af_grid.ascx(46): error CS0103: The name 'GetLastRead' does not exist in the current context

Does that happen to you guys too?

**Comment by supermansrf** [comment]
Try reinstalling the PA.  I've seen something similar to this before and I believe that it was due to a bad upgrade. Reinstall the package and see what happens.

**Comment by cmsfrotter** [comment]
Unfortunately no change at all with repair, but reinstall does indeed get it to work again. Since threads are viewable even with a bad upgrade I think content tables are not the problem here. So I'd assume it's safest to do the upgrade, backup all AF tables, reinstall, apply the backup and update the ModuleIds on every activeforums_* table to match the new one?

Anyways, tested out the changes with a reinstall. Seems to work properly now, so I created a pull request.
