### ISSUE TITLE
Allow media embedding with CKEditor?

### ISSUE THREAD

**Issue by TBGoat** [ActiveForums/ActiveForums#255]
So, I tried to let my users use the CKEditor youtube (media) embedding.  It seems to work fine, but after they hit submit, a container shows inside the forum window and displays a "cannot find the page you were looking for" error.

Has anyone managed to make this work?  Is there a setting I need to tweak?

**Comment by supermansrf** [comment]
Go look at how ckeditor is inserting the link. It's a mess. 

I've yet to figure out how to fix it without manually editing their post for them and changing the html manually. Not to mention it's not responsive. So the videos are showing up fixed width. 

This was on my list of things to do. But haven't gotten around to asking Ingo over on the ckeditor project. 

When I'm stopped later tonight I can give you specifics if you still need them. But I know it inserts messed up code. Like it overthinks it a bit. Or at least that's what I remember (a bit foggy lol)

**Comment by supermansrf** [comment]
Side note - I would love to eventually build an editor into AF. Something that would solve a lot of these problems. But I've been waiting to see what DNN does with their new integration of CK. But better than the one they did build in.

**Comment by TBGoat** [comment]
Thanks. I ended up putting an HTML note above the forums telling them to just copy the embed code and paste it in.  Not the most elegant, but it will work for now.

Its a shame, CKEditor seems to work really well for most things - and it works for inserting media in the plain HTML modules.  But, it sounds like one of those things that are more hassle than they are worth to fix at present.

**Comment by maduranga001** [comment]
When we post the Embed code and submit, it removes the "https://" part from the code when saving. This is why the code is not working after we submit it. Please advise for this.

**Comment by supermansrf** [comment]
@maduranga001 what html editor are you using?

**Comment by maduranga001** [comment]
CKEditor

**Comment by supermansrf** [comment]
The problem is with ckeditor not AF. 

I posted over there once I believe and asked this. Need to check

**Comment by cmsfrotter** [comment]
Did you try using a different embed plugin? I think there were more than one, especially for youtube. I may give it a try if I get some time.
