### ISSUE TITLE
File upload

### ISSUE THREAD

**Issue by fahadhaq** [ActiveForums/ActiveForums#257]
Trying to upload a file as an attachment for forum. But keep getting the following error.

Server cannot set status after HTTP headers have been sent.

Full error below. Can some one please help fix this for me.

Event code: 3005 
Event message: An unhandled exception has occurred. 
Event time: 4/15/2015 12:59:48 PM 
Event time (UTC): 4/15/2015 12:59:48 PM 
Event ID: d6fe3496fd394bccb81ae337c662cf23 
Event sequence: 10 
Event occurrence: 1 
Event detail code: 0 

Application information: 
    Application domain: /LM/W3SVC/1/ROOT-1-130735763389079094 
    Trust level: Full 
    Application Virtual Path: / 
    Application Path: C:\inetpub\wwwroot\DNN_****_l\ 
    Machine name: ***_******

Process information: 
    Process ID: 2532 
    Process name: w3wp.exe 
    Account name: IIS APPPOOL\DNN 

Exception information: 
    Exception type: HttpException 
    Exception message: Server cannot set status after HTTP headers have been sent.
   at System.Web.Http.WebHost.HttpControllerHandler.EndProcessRequest(IAsyncResult result)
   at System.Web.HttpApplication.CallHandlerExecutionStep.OnAsyncHandlerCompletion(IAsyncResult ar)

Request information: 
    Request URL: http://stage.**********.com/DesktopModules/ActiveForums/API/ForumService/UploadFile 
    Request path: /DesktopModules/ActiveForums/API/ForumService/UploadFile 
    User host address: 118.92.30.204 
    Is authenticated: True 
    Authentication Type: Forms 
    Thread account name: IIS APPPOOL\DNN 

Thread information: 
    Thread ID: 18 
    Thread account name: IIS APPPOOL\DNN 
    Is impersonating: False 
    Stack trace:    at System.Web.Http.WebHost.HttpControllerHandler.EndProcessRequest(IAsyncResult result)
   at System.Web.HttpApplication.CallHandlerExecutionStep.OnAsyncHandlerCompletion(IAsyncResult ar)

Custom event details:

**Comment by artfuld** [comment]
Hello @fahadhaq do you have any other module with file upload?
This sounds like a server-side permissions problem.

**Comment by fahadhaq** [comment]
I have document manager and that seems to upload files just fine. I have checked all my permission but not sure if I missed anything

**Comment by fahadhaq** [comment]
Just wondering where is the following file located as I cant seem to find it any where is the system

uploadServiceUrl: '/DesktopModules/ActiveForums/API/ForumService/UploadFile',

**Comment by artfuld** [comment]
@fahadhaq You can find that in Services/ForumServiceController.cs
Line 87.

**Comment by fahadhaq** [comment]
so it seems the issue is my end. The problem I am facing is that whenever I make an ajax call it seems to log out my portal user. I know this is not the right place to ask but is there a way to fix this? I have got 'Page State Persistence' set to page but nothing changed. Do I need to change any other settings?

My portals are created as following

http://www.mywebsite.com/<portalname>

**Comment by artfuld** [comment]
I don't have an answer for you unfortunately.
But the address you're linking to can't be found. Is it some sort of free webhosting?
