### ISSUE TITLE
Create custom Topic Form Template

### ISSUE THREAD

**Issue by ericktj** [ActiveForums/ActiveForums#260]
Hi there

Any advise when creating a custom Topic Form Template ?

I made a research within this forum about it but couldn't find anything - I basically just want to add 3 more fields to the Topics Form

Thank you

**Comment by supermansrf** [comment]
Give me a little more info on what you are trying to accomplish? What exactly are you trying to do?

**Comment by ericktj** [comment]
Hi supermansrf, Thanks for the quick reply

What I want to do is add 3 more fields (Text Boxes) above the Subject field, they will be require to in order to add a new Topic and I would like to be able to show them in a new Topic View Template as well. 

I know a bit of programming (I developed some simple DNN modules before) and been checking the source code files but I'm a bit confused and not sure where to start

Thanks

**Comment by artfuld** [comment]
![image](https://cloud.githubusercontent.com/assets/6116748/7386830/5b475c92-ee58-11e4-9d34-06fee5bccb62.png)
Is it something like this that you're asking for @ericktj ?

Hard to see now because of my css is a bit weird but there's 3 more input fields there, 2 that takes text and one yes/no.

If this is what you want you can add it dynamically to your forum in control panel -> Forums -> your forum -> Topic Properties
 
![image](https://cloud.githubusercontent.com/assets/6116748/7386856/adb84e6e-ee58-11e4-95ca-9d6f5a656b03.png)

**Comment by ericktj** [comment]
Oh Wow, I wasn't aware of that facility of the module

Thank you guys

**Comment by ericktj** [comment]
Hello, sorry artfuld I had to reopen this issue because I'm adding 3 Properties I needed as I mentioned above, the Properties are added correctly to the Topic Form when trying to add a Topic, the problem is that the fields just wont be saved, actually if I add text to the Properties ( text fields) , the whole Topic wont be created, I need to delete text on Properties so the Topic can get created

Is this a known issue, ? Any advise on this one ?

Sorry if I post a lot, just working on a project using this module right now

**Comment by supermansrf** [comment]
@ericktj don't be sorry for posting a lot.  I'm glad there is discussion. Its way too quiet around here.

**Comment by artfuld** [comment]
@ericktj as long as you understand that this is an open source project, you don't have any reason to say sorry :).

I have not had this problem, did you add 3 textfields? what was the names of them. More info is needed so someone can try to recreate the problem.

**Comment by ericktj** [comment]
hehe Thank you guys, sure, I understand is an open source, just posting hoping to receive some advise from any good Samaritan at some point :D, 

I'm sending screens of Properties

![image](https://cloud.githubusercontent.com/assets/12074845/7544689/2e86c58e-f584-11e4-9cfe-606e5fe63e7e.png)

![image](https://cloud.githubusercontent.com/assets/12074845/7544698/5136bada-f584-11e4-93e3-aa1467c1dbc3.png)

![image](https://cloud.githubusercontent.com/assets/12074845/7544704/66d130c8-f584-11e4-8674-0a02b45b7e51.png)

**Comment by artfuld** [comment]
I can reprodude that error, I'll take a look at it and see if there's something I can do to fix it.

**Comment by artfuld** [comment]
Ok, I narrowed this down to the input validation. If you remove any text in that textbox everything should work fine.
I'll try to look up why this problem exists when I got time.

**Comment by ericktj** [comment]
Hello, just checking if you guys found anyting ?

I got to tell you guys that I just got the module installed (Added with the Installation package) in my DNN , but I want to setup the whole solution and be able to make changes to it, and why not help the this forum taking a look at some issue (not much advanced)

I'm planning on doing that this week.
