### ISSUE TITLE
Posting/Inserting inline photos & Emoticons

### ISSUE THREAD

**Issue by gitmoregrits** [ActiveForums/ActiveForums#261]
Hi folks, we have a site using AF and are up on the latest beta release.  First off, thanks to the folks who are keeping this going and alive.  It's truly much appreciated.

We're having a couple of issues:

1)  How do you actually insert a .jpg or .png, basically a picture, into a forum posting.  Attachments are working fine but how does one go about an insertion so that it displays inline within the forum topic posting?
2) With the emoticons, how does one actually select them for display in a forum posting?  I've only tried with IE and I cannot get anything to work.

Thank you very much,

Patrick Arnold

**Comment by artfuld** [comment]
Hello!

1. We use ckeditor and their built in image handler to insert an image to a post.
![image](https://cloud.githubusercontent.com/assets/6116748/7417940/1af26322-ef6a-11e4-81e0-ad6aa9926fba.png)

2. You should just be able to click them and they should show up in your post. I tried with IE now and it works fine for me.
Are you talking about the smileys on the side of the texteditor or do you mean the Post Icons above the texteditor?

**Comment by supermansrf** [comment]
So the problem that we have with our forums is how CKEditor's permissions work.  I don't want to give my users access to the server except within their own folders.  So we have used the option "use subdir for non-admins" and specified a users folder on the server. They have access to an upload folder of their own.  This seems to work ok for everyone except admins.  Admins get dumped into the users root folder and can't see any of the other folders on the server which isn't great but doable. I simply upload via ftp to where I want the files then specify by url.  

However, the attachments feature works just fine and is a whole lot easier in my opinion.  I still don't know where these files go (on the server), but when you attach an image, there is a + sign to insert into the post.  Then it appears inline.

With the emoticons all you have to do is position your cursor where you want it and click on the image.  I also feel like a recent upgrade to Internet Explorer has started to cause issues with pretty much everything DNN so if you are using IE that may be the problem.

**Comment by artfuld** [comment]
@supermansrf I did not know that function was working again, if that's so then I don't recommend using the ckeditor-upload!
Just checked my dev-setup and it works like a charm! Good catch

**Comment by gitmoregrits** [comment]
Thanks for the engaging conversation, all!

Okay, it would seem IE is causing the emoticon issues.  I'm running IE 11.  In AF, I don't see the "+" to insert an image although I see the words "insert image" as depicted in the two provided screenshots.  So the net-net is I can insert an emoticon with Chrome but cannot with IE, and I still cannot seem to insert an image, inline, regardless of browser.

![Uploading Chrome_AF_Post.png…]()
![Uploading IE_11_AF_Post.png…]()

**Comment by artfuld** [comment]
Looks like this has something to do with old code. @gitmoregrits is this a new install for you or an updated forum?

**Comment by artfuld** [comment]
Ok. so it seems like my production site doesn't have the jquery-ui package installed (or some other package).
edit. This doesn't work with glyphicon either so there's probably something else that's wrong

@gitmoregrits can you try to change inside your af_attach.ascx (should be in desktopmodules/activeforums/controls) on line 45. Just add a "+" before the </td>
<td><span class="ui-icon ui-icon-plus" data-bind="click:$root.insertImage" />+</td>

This made it work for me, the problem as I see it is that it will show up now even for non image files and try to add it as an img inside the post.
I will try to dig deeper in to this and see if I can find the real problem.

**Comment by artfuld** [comment]
Ok, my issue was that I was using a different theme. My theme wasn't loading jquery-ui.ccs
So what I ended up doing was to copy the content of jquery-ui.css to af/themes/mytheme/module.css. and then copy af/themes/_default/images/ui-icons* to af/themes/mytheme/images/

For some reason I also had to add display: block; to the style for .activeForums .ui-icon

**Comment by gitmoregrits** [comment]
Art, do you recommend I still add the "+" per line 45 of af_atttach.ascx?  Thank you.

**Comment by artfuld** [comment]
if you do what I did in my last post then you don't need the "+".

Did you also have another theme?

**Comment by gitmoregrits** [comment]
Art, thank you for being so helpful.  I managed to make the latest changes you suggested with the exception of: "For some reason I also had to add display: block; to the style for .activeForums .ui-icon".  My apologies, but I'm struggling a bit to figure out what you're saying here.

**Comment by artfuld** [comment]
@gitmoregrits sorry for being away, did you get this fixed?
