### ISSUE TITLE
A server error has occurred

### ISSUE THREAD

**Issue by supermansrf** [ActiveForums/ActiveForums#265]
So i'm freaking stumped.  Maybe I'm brain dead.  I don't know.  I upgraded a site tonight from AF 5.2.3 to 6.1.5 no issues.  

The reason for the upgrade was to take advantage of the attach/insert function that we implemented.  I've had no issues with this on other sites. Setup everything in the database, made sure to allow the proper extensions, number of files, file size.  Here is where it gets stupid.  

One of my admins can upload via the attachment area. My host account cannot.  I get "a server error has occurred" with no other warning.  

Anyone have any ideas?  I'm frustrated.

**Comment by artfuld** [comment]
Have you checked the server logs if there's anything logged?

**Comment by supermansrf** [comment]
Yes sir. Nothing at all.

**Comment by artfuld** [comment]
I'm gonna set up a new dnn dev and see if I can replicate. Are you using the latest version of DNN?

**Comment by supermansrf** [comment]
DNN 7.3.4 - if you want, send me an email and I'll give you access to the site.

**Comment by supermansrf** [comment]
So i've done some more testing, and have found that its only my host account that can't attach (when I get the error message).  Admin account and a regular user account doesn't get the error and is able to attach and insert just fine.  

I'm going to test this on a few other sites today and see what happens.  I don't normally use this feature.  I upload via ftp and insert manually with html, so i bypass all features that are used by my end users typically.  It makes things easier for me as I do a lot of file transfer and just use my native tools to drag and drop where I want things on the server.  So I don't know how this normally functions for the host account.  But I still find this strange.  

Does anyone know where these files go when we use the attachment function?  Are they put into the database or a folder somewhere?  Any thoughts on this?  I'm just wondering if they do go to the database, if this is the best place for them.  It seems to me that hundreds or thousands possibly more users uploading images to the database would make things really big at some point.  Especially if there are no restrictions, compression etc on files.  Someone uploading even 5mb photos can take up a ton of room with many posts.

**Comment by artfuld** [comment]
If you create a new host account, will the same thing happen?

**Comment by artfuld** [comment]
The uploaded files are save to 
\portals\_default\Users\001\01\1
Guessing _default is based on the portal, and the numbers are from the users ID

**Comment by artfuld** [comment]
Just remembered, I had a problem on my live site that some users didn't have the folder allready set up.
But I think that was a problem with the ckeditor upload. But might be worth checking out.

**Comment by supermansrf** [comment]
Good call @artfuld I setup a new host account and it works fine.  So its apparently something to do with the stock host account.  Interesting but what does this mean?

**Comment by artfuld** [comment]
have you checked the maps that the files are supposed to upload to? Check if there's a folder for your hostaccount.

**Comment by supermansrf** [comment]
Any idea what the host account folder location is?  You're probably right.  It looks like my other host account is uploading to its own folder.  So what is the default folder for host?  Is it users/001/01/1?

**Comment by artfuld** [comment]
001/01/1 was for my host, Not sure why there's 3 dirs..
