### ISSUE TITLE
Missing {databaseOwner}{objectQualifier}

### ISSUE THREAD

**Issue by deskpal** [ActiveForums/ActiveForums#267]
Hi All,

This is minor but an issue nonetheless:

The SP "activeforums_Reply_Save" is missing {databaseOwner}{objectQualifier} in front of activeforums_Topics and activeforums_Content on lines 38 and 39 inside script file 06.00.02.SqlDataProvider

This is breaking an installation I have for a client which is using an object qualifier for their tables.

Best regards,
Aderson

**Comment by artfuld** [comment]
Thanks, this will be incorporated in the next version.
