### ISSUE TITLE
Verion 6.2.0 released

### ISSUE THREAD

**Issue by supermansrf** [ActiveForums/ActiveForums#269]
I have compiled and released version 6.2  I'm not going to be redundant and type it all out again.  I'm leaving this topic open for feedback on the new version.  

READ THE COMMENTS I LEFT WITH THE RELEASE.  This is a BETA.  Do not use on production site until you know how it is going to react or without a backup to revert to.  Again you have been warned.  

Please give us as much feedback so we can get this aimed at a stable release very soon.  Its been too long.  Thanks @artfuld and @laralmix for helping to get this out.

**Comment by supermansrf** [comment]
So first glance I'm having some small issues.  I upgraded a forum (test site).  The first install caused issues.  I was seeing tokens and random icons rather than what I should see.  A reinstall fixed the issue.  

We are still plagued with the whole "need to reinstall" it seems.  This would be something good to look into.  See why this is happening.  So far though, this looks great.

**Comment by artfuld** [comment]
Nice! I will install today and let you know if I have any problem.

**Comment by artfuld** [comment]
The new UI looks good! Had no problem on a new installation.

**Comment by Plumifrons** [comment]
Good to see that you have made progress with the UI. I will do some testing the coming days.

**Comment by Plumifrons** [comment]
If there is a pane to the right of the AF module the lay-out is not correct.
![2015-05-16 13_05_52-test 1 - my website - af - default group - sample forum 1 - internet explorer](https://cloud.githubusercontent.com/assets/5980007/7665893/a08c99b2-fbcc-11e4-94c5-68f1c88c32de.png)

**Comment by Plumifrons** [comment]
Wrong tooltips.
![2015-05-16 13_10_24-my website - af - default group - sample forum 1 - internet explorer](https://cloud.githubusercontent.com/assets/5980007/7665901/15d87b82-fbcd-11e4-9261-3d338718e207.png)

**Comment by Plumifrons** [comment]
The topic text in topics view is after the icons. I think it is better to have them under the icons to make better use of the available space.
![2015-05-16 15_36_25-my website - af - default group - sample forum 1 - internet explorer](https://cloud.githubusercontent.com/assets/5980007/7666323/d112bc6e-fbe1-11e4-98a4-70ebc1629873.png)

**Comment by Plumifrons** [comment]
Is it possible to have bigger icons on mobile device? The current ones are to small for touch screens.

**Comment by gitmoregrits** [comment]
Thanks to @supermansrf,  @artfuld, and @laralmix for getting this beta release out!  It's much appreciated!

Question: Does anyone ever provide access to a test/demo site that we can simply look at for a quick view of a given release?

**Comment by supermansrf** [comment]
activeforums.org is running 6.2.1

**Comment by gitmoregrits** [comment]
Grossly overlooked; apologies, thank you!

**Comment by supermansrf** [comment]
Issues fixed in later builds
