### ISSUE TITLE
Version 6.2.2 released

### ISSUE THREAD

**Issue by supermansrf** [ActiveForums/ActiveForums#276]
I just released version 6.2 Beta 2 (06.02.02).  I have done some testing with this and am happy with it.  

I would appreciate any feedback.  Also since 6.2 was a major UI rewrite, some may have issues getting the postinfo template ironed out. I did.  If anyone wants to see what I use for my template let me know.  There are some classes that are setup and ready to handle anything other than the avatar when in mobile view.  

This also fixed some issues with tooltips, as well as content running outside of the container. Enjoy!

**Comment by Plumifrons** [comment]
In Chrome the contents stays in the pane but in IE and FF not.
![2015-05-25 10_46_41-picture 1 - my website - af - default group - sample forum 1 - internet explorer](https://cloud.githubusercontent.com/assets/5980007/7794638/d60e98c2-02cc-11e5-81fa-2b916f95deb0.png)

**Comment by supermansrf** [comment]
Issues fixed in later build
