### ISSUE TITLE
6.2 Beta 3 release

### ISSUE THREAD

**Issue by supermansrf** [ActiveForums/ActiveForums#278]
I have uploaded beta 3.  I am now using these on all of my production sites.  I still have a few small issues but nothing keeping me from using them in production.  Hopefully we can get some good testing, flush out any final UI related issues and move this to stable. 

I appreciate those of you who are trying these out and reporting back.  It really helps as I'm limited on what OS and browsers I can test on.  Since I've moved my main site over I'm sure I'll be getting 4000 or so opinions over the next week or so.  I would love to have a stable within a week.  

Thanks @laralmix for keeping these moving.  

Enjoy!

**Comment by Plumifrons** [comment]
6.2 Beta 3
The picture is now also looking good in IE and FF. Good job.
I see only a small issue with one icon.
![2015-05-25 22_19_52-picture 1 - my website - af - default group - sample forum 1 - internet explorer](https://cloud.githubusercontent.com/assets/5980007/7801909/d9b85606-032c-11e5-9aa8-9caddedd4525.png)

**Comment by supermansrf** [comment]
That icon was fixed a few releases back. Is it possible your template is off?  

Or try a reinstall. I have to install twice each site I have and each release I install. Still trying to determine if it's my server or the software.

**Comment by Plumifrons** [comment]
New DNN 07.03.04
Installed Beta 1 --> Beta 2 --> Beta3
Then you see the big icon.

Then I installed Beta 3 again and the icon is okay. Strange.

**Comment by Plumifrons** [comment]
The post icons are not showing in the topic list.

**Comment by Plumifrons** [comment]
The smileys are smiling a little to big.
![2015-05-25 23_05_50-post icons 1 - my website - af - default group - sample forum 1 - internet explo](https://cloud.githubusercontent.com/assets/5980007/7802279/ca645bfe-0332-11e5-8341-57828d6b3a01.png)

**Comment by Plumifrons** [comment]
Did some testing on my android mobile and it is looking very good.

**Comment by supermansrf** [comment]
Moved to 6.2.4 release
