### ISSUE TITLE
Sort function not working

### ISSUE THREAD

**Issue by gregclemens** [ActiveForums/ActiveForums#287]
Under "My Settings", selecting "oldest" sort order doesn't seem to work.  Using v6.1.5 in DNN 7.04

Additionally, can the admin select a default order?  If so, I'm not sure where.  Thanks.

**Comment by artfuld** [comment]
Hey Greg,
The sort order is for how the posts are shown in a thread.
![image](https://cloud.githubusercontent.com/assets/6116748/9112600/d0dbfc8e-3c4f-11e5-8027-d352d9a33578.png)
Oldest first.

![image](https://cloud.githubusercontent.com/assets/6116748/9112611/e09430d8-3c4f-11e5-83e2-1754219e82df.png)
Newest first.

**Comment by artfuld** [comment]
The default value for sort order is set in the database, not sure how familiar you are with sql but it's quite simple just just have to change the default value for PrefDefaultSort in activeforums_UserProfiles to 'DESC'

Or you could change this from inside dnn.
ALTER TABLE {databaseOwner}[{objectQualifier}activeforums_UserProfiles]
DROP CONSTRAINT DF_activeforums_UserProfiles_PrefDefaultSort
GO


ALTER TABLE {databaseOwner}[{objectQualifier}activeforums_UserProfiles]
ADD CONSTRAINT DF_activeforums_UserProfiles_PrefDefaultSort default 'DESC' for PrefDefaultSort
GO
