### ISSUE TITLE
Page load enhancement

### ISSUE THREAD

**Issue by gregclemens** [ActiveForums/ActiveForums#288]
I've noticed something about how this module operates and wondering if this might be an enhancment that others would like.  I have a banner module above my AF module that sort of introduces the Forum.  When a user clicks a topic the banner must re-load along with the AF module below it.  You have to scroll down to the topic each time including if I click on comments below each topic.  Wouldn't it be preferential to just have the topic and comments load to a new page minus the banner?

**Comment by johnhenley** [comment]
i do something similar, but put what your calling the banner module into a sidebar pane, and enable users to expand/collapse it so it doesn't take extra screen space. Also have that module set with a lengthy cache lifetime so it doesn't have to reload from the database every time the page loads.
