### ISSUE TITLE
Attachments not working in child portal

### ISSUE THREAD

**Issue by lfreer** [ActiveForums/ActiveForums#289]
When I add the module to a page in a child portal, I get a 401 Unauthorized error when trying to add an attachment. I have tried this as both host and a regular user. Attachments work fine when the module is in the root portal.

**Comment by artfuld** [comment]
There seems to be alot of problem with group/forum settings for a child portal. I can't even get the attachments-pane to show for my test user.

**Comment by artfuld** [comment]
Closing due to duplicate #392
