### ISSUE TITLE
Exclude Forum from Not Read?

### ISSUE THREAD

**Issue by PatrickMcCrann** [ActiveForums/ActiveForums#290]
We use two specific forums for users to post questions / feedback, this is a great way to keep a public record...BUT...when someone else hits "Not Read" they then see all the replies to this forum that they otherwise wouldn't read (they would only read their personal thread).

Is there a way to exclude a particular forum from that Not Read listing? 

Many thanks!

**Comment by artfuld** [comment]
Hello Patrick.
The not read shows from every forum that the current user have access to. Right now there's no way to set not read to only show from a particular group or forum.
