### ISSUE TITLE
Forum View showing [ICONPIN][ICONLOCK] 

### ISSUE THREAD

**Issue by TBGoat** [ActiveForums/ActiveForums#291]
It looks like the last upgrade to 6.1.5 (or maybe sooner and no one noticed) seems to be missing some icons.  At least I'm guessing that's what this is?

Next to every topic tile we see : [ICONPIN][ICONLOCK] 

Are these somewhere that I can grab them and just upload them to the right directory?

Thanks

**Comment by supermansrf** [comment]
Do a repair install of the module. That will fix this. I have been
having to install each release twice in order to get things to update
properly for a while now.

**Comment by TBGoat** [comment]
Thanks, that worked on the second reinstall.  Very strange.
