### ISSUE TITLE
tokens not populated

### ISSUE THREAD

**Issue by teambound** [ActiveForums/ActiveForums#295]
I am working with the latest release and have noticed that tokens are not replaced for the following:
[ICONPIN][ICONLOCK]
[SPLITBUTTONS] 
[ACTIONS:MOVE]
[LIKESx2]
[SPLITCHECKBOX]

How do you turn on the likes? I check it in settings but it does not save.

**Comment by supermansrf** [comment]
You need to do a repair install. Each release (until this is fixed)
appears to require a repair install to get everything to populate
correctly. No clue why yet.

**Comment by teambound** [comment]
gotcha - all set. Thanks.
