### ISSUE TITLE
AF Topic Post | Insert Image | OK on Chrome and FF --not working on IE

### ISSUE THREAD

**Issue by gitmoregrits** [ActiveForums/ActiveForums#297]
The subject pretty much says it all.  Running the latest build of AF.  Inline insertion of images works on Chrome and FF but not on IE.  With IE all I can get to work is an image as an attachment.

**Comment by supermansrf** [comment]
I realize this isn't much of an answer, but here is my take on this.  I have several large sites.  One with a forum that has well over 3500 daily active forum users and about 500k posts.  We have members from all over the world, including a few who work for the IE team at Microsoft.  

I also use Smith Consulting Buy Now module, which is ALWAYS kept up to date at each release as soon as it is released.  This is an expensive module while their decisions may be questionable at times.  But I almost ALWAYS have issues with IE.  I have gotten to the point after IE 9 came out that I honestly put zero effort into troubleshooting IE issues.  It is the first question I ask when I am confronted with "(fill in the blank) isn't working".  If their answer is IE I immediately tell them to download Chrome or Firefox.  

We have spent probably $7500-$10000 on the Smith Buy Now module, paid customizations, upgrades and support in the past 2 years.  Right now anyone using IE can't finish a payment.  It just spins and spins and does nothing or they can't even see certain components of the store module.  Now I have found that if you add the URL to the compatibility list it sometimes helps but not often enough to provide a stable solution.  

Our members that work for Microsoft absolutely hate it when I endorse Chrome but when I was asked by them why my answer was really simple.  IE sucks.  We could work all week to get the bugs worked out and next Tuesday night when updates are rolled out its broken again.  I just give up.  

Not trying to tell you what to do, but that seems to be the path of least resistance at least for me.  Doesn't make sense considering DNN is technically all MS based but whatever.  Maybe I'm just a snob.  

I would be curious to know what you find out if you find out anything.  I would like to ensure we are compatible with all browsers, but from my understanding keeping up with IE is going to be kinda hard.

**Comment by gitmoregrits** [comment]
I understand or at least acknowledge why you feel the way you do.  I work for Microsoft and while not in IE I do have an IE app compat expert on my team who may be able to help guide this along to the right folks in IE.  Perhaps we can follow up offline w/ one another to see if there is a known core area that is suspected to violate or be incompatible with whatever FF/Chrome are doing well --whether a standard or not.  What do you think of this approach?

**Comment by supermansrf** [comment]
Absolutely.  I would do whatever it takes to make this more IE friendly.  Like I said it blows my mind ALL of the random IE issues that exist within a primarily Microsoft based solution.

**Comment by supermansrf** [comment]
I believe my email is public on here if you want to reach out.

**Comment by gitmoregrits** [comment]
Seth, I sent you an email --may want to check your junk folder.  One of my guys has figured out the IE image insertion issue.  He thinks it's likely affecting the emoticon insertion logic too.   He's got the code fix as well as a workaround.

**Comment by passfire** [comment]
supermansrf,  I've found the best way to deal with SmithCart bugs is to stop using SmithCart.  As you've found, their pricing scheme is a never ending money hole.  Not only is it buggy, but it breaks when new versions of DNN are released and their absurdly short free upgrade period results in you continually having to buy the software again at full price, or miniscule discount.  It sounds like you are pretty invested at this point and can't justify change, but on any new projects check out Cart Viper instead.  I've had much better luck with that product.  IE is still a major browser brand, you can't expect customers to abandon it.  They will most likely abandon your site before they switch browsers.
