### ISSUE TITLE
Community question about forum/topic/post icons - answer if you have an interest in this

### ISSUE THREAD

**Issue by supermansrf** [ActiveForums/ActiveForums#299]
So I've been working with the guys who are making the UI changes as well as implementing them on my forums.  I have been going in and modifying my sites to remove the forum icons, topic icons, post icons.  To me these are worthless.  There is no way of changing them, and they are ugly in my opinion.  

Would anyone be truly upset if we ditched the icons?  I honestly don't see a need for them.  It isn't the icon that is going to get people's attention.  In a forum like ours, we have an area for general discussions, an area for questions or support, an announcement forum.  So all of the posts in a certain forum are the same.  The icons just seem like it was cool back when this was built but now they seem like a waste.  There is no way of changing them and they take up valuable real estate when in mobile and tablet view.  

I have been working with this last release and while its better there is still some work.  One of the things I have thought about doing is getting rid of the icons completely (nothing other than forum, topic, or post icons).  

What does everyone think about this?

**Comment by allanedk** [comment]
Well, I don't agree with you on this one.

I think they are important as they indicate whether the user has unread posts in a thread. And you can easily change them by adding new png/gifs. However it would be better if they where handled through CSS instead of a IMG-tag. By using CSS you would be able to position them easier and alter the image used easier. Plus you could hide them on mobiles using a responsive theme.

So in my opinion they should stay, but "moved" to a CSS class.

**Comment by artfuld** [comment]
The icons are one of the best feature of any forums, easy to see if there's a new thread in a forum or a new post to a thread.
I think that you will lose many af-users if you remove thoose icons.

I agree with @allanedk that they should be changed to being set up by css.

**Comment by Plumifrons** [comment]
My first thought was I use them even with different icons so they must stay. But I don’t really look to them if there are unread posts. If you can move them to CSS as Allen suggested it would be great but if you remove them it is fine with me. 
![2015-06-26 12_21_54-anemoon _ mijn anemoon _ forum - internet explorer](https://cloud.githubusercontent.com/assets/5980007/8375774/a23a0ab6-1c00-11e5-88f8-a5d9afb1e16b.png)
