### ISSUE TITLE
Release 6.2.5 - still a few issues

### ISSUE THREAD

**Issue by supermansrf** [ActiveForums/ActiveForums#300]
There are still a few issues with what 6.2.5 was aimed at fixing.  I still don't see latest post in forumview, or topics view. So we still have some work to do.  It definitely helps with the active topics area, but there are a few areas that we missed.

**Comment by cmsfrotter** [comment]
Guess that is also the reason why I get a massive amount of unknown column name errors when trying to backup the existing 6.2.4 SPs, right? e.g. TopicView tries to
SELECT [..] A.PostID [...]
FROM        dbo.activeforums_Attachments AS A [...]
but there is no PostID in that table, at least in my (repair-installed) version of that table. I'm getting a truckload of similiar errors for other SPs (and for some reason the sqlserver doesn't like to backup these as is). Is this already being looked over? Since I don't really know where this is headed - or coming from for that matter - I naturally don't want to mess with anything in progress. Haven't looked at 6.2.5 atm though, so maybe it's already done

**Comment by supermansrf** [comment]
So I'm a bit confused.  I have a few questions:

When I made the statement there were still a few bugs, I was referring to several UI related issues that I was having.  This last change added the last post column back into the tablet and mobile view (mobile view mainly).  It was all cosmetic changes, nothing mechanical so to speak.  So I can assure you that 6.2.5 doesn't fix it. 

Are you referring to just a normal Management Studio backup that is failing and you are saying it has something to do with the database?  For what its worth, I have several sites, most of them are running a scheduled backup on 15 minute increments.  None of them are erroring out, ever.  But you are far more advanced than I am on any of this.  

And to answer your question, no nobody is working on this.  The development of this module could really use assistance from anyone willing to help.  I have a few developers who work for me (paid by the hour) that I contribute to the community as often as I can, but I'm primarily focused on the user interface right now and making the responsive design more efficient and better.  

I'll go ahead and comment about your pull request too while we are talking about this.  I have spoken with a few of the regulars around here privately.  While I'm not saying no, we don't know what your pulls fixed with the exception of the notes that you put on here.  The problem is that you included a fix along with a new feature.  Something that a few of us weren't familiar with.  FYI I'm referring to #262 & #283 

It appears to me, that you have fixed the SQL deployment as well as added a new feature called "Unresolved" & "My Resolved" views.  

While I will not argue that anything that fixes things in the database is much needed, this new feature is something that not everyone will use.  I'm not sure if there is anything that we can do to provide this as an option maybe?  

Regardless, anything that you are willing to do to help the project out I'm open to letting you do.  I will take all of the help I can get.  I would just like to discuss this a bit more before just adding something that may or may not be easily removed for those who don't want it.  

If you would like to continue this discussion privately, I'm more than willing to talk to you and would definitely appreciate the extra help.  Including anything that you see is causing issues.  If its happening to your setup, chances are its happening to someone else.  

You can find my email from my profile here.  Feel free to reach out.

**Comment by Plumifrons** [comment]
The emotions are fixed but the bigger pictures are again to big. 
![2015-07-09 20_32_45-picture w4 - my website - af - group 1 - sample forum 1 - internet explorer](https://cloud.githubusercontent.com/assets/5980007/8603715/4c8e14b6-267a-11e5-9b7a-1f96a95e5b27.png)

**Comment by supermansrf** [comment]
@Plumifrons please see if this is still happening in 6.2.8 and if so lets get the info on a fresh comment so it doesn't get lost.

**Comment by Plumifrons** [comment]
It is working now see #309
