### ISSUE TITLE
Moderator "Post Pending" emails never sent

### ISSUE THREAD

**Issue by lfreer** [ActiveForums/ActiveForums#302]
WE have an issue where a moderated forum is not sending any emails out to notify users with "ModApprove" permission that there is a post awaiting approval.
We have confirmed that no email is ever even attempted to be sent from the program.
How do we set up so a Moderator account is notified?
I have "Moderated" on and a user with ModApprove permission and the "PostPending" template set to be used

**Comment by artfuld** [comment]
I have checked this out and from what I can see AF doesn't send emails, but it creates a notification in DNN. If you get emails it should be from DNN when you recieve a notification.

**Comment by lfreer** [comment]
So what is the point of having a PostPending template if it never gets used?

**Comment by artfuld** [comment]
My guess is that it's some code that's left behind since before active social. I will have a look at this and make sure that it's deleted (or atleast hidden) if it's legacy code.

**Comment by artfuld** [comment]
I get an email from dnn when there's a post that needs approval, but it's from the notifications.
I think that the templates was from before when there wasn't a journal/notification builtin to dnn.

What you can do for now is editing what is sent to the notifications in the language editor
Local resources - DesktopModules - ActiveForums - App_LocalResources - SharedResources
There you find the templates for bort Subject (NotificationSubjectReply) and Topic (NotificationSubjectTopic)

Personally I liked the old moderator system better, but that's probably cause I don't use the Journal/Notification ever.
