### ISSUE TITLE
Moderate new topics only instead of moderating both topics and posts

### ISSUE THREAD

**Issue by AFGfK2002** [ActiveForums/ActiveForums#303]
Hi, I am working with DNN Platform 07.04 and AF 5.2.2 and I have a problem with the moderation in general. It seems that it is only possible to moderate both new topics and posts rather than new topics/threads. Can anyone help me with this problem? Thanks in advance.

**Comment by supermansrf** [comment]
Moderation is something that hasn't been really talked about much on here.  I also don't fully understand what you are saying here.  Can you elaborate on this a bit more so I can get a clear picture?

**Comment by artfuld** [comment]
You want to moderate only the first post in a thread and answers in that thread should be automatically allowed, do I understand that correct?

This sounds like a really bad idead, when and how would you use this?
