### ISSUE TITLE
AF 6.24 - Emoticons turn into giants

### ISSUE THREAD

**Issue by gitmoregrits** [ActiveForums/ActiveForums#304]
I know we're beyond this release now but has anyone else seen this?

If folks want to see this first hand (link is public for now) on my site you can do so here: http://awc-web-server-1.cloudapp.net/forum/aft/2775

Scroll down a bit for "giant" emoticons :/

Regards,
Pat Arnold

**Comment by supermansrf** [comment]
Refer to #281 the solution is in the replies.  Also it was fixed in 6.2.5

**Comment by gitmoregrits** [comment]
Okay, thank you.  My apologies for the extra cycles in setting me straight!

**Comment by supermansrf** [comment]
All good.  Its not like things are easy to find on here.  I'm almost done.  I'll be calling you in about 15

**Comment by supermansrf** [comment]
@gitmoregrits are you ok with me marking this closed?

**Comment by gitmoregrits** [comment]
Yes, you can close this.
