### ISSUE TITLE
Bug in Attachments in the Moderator queue

### ISSUE THREAD

**Issue by lfreer** [ActiveForums/ActiveForums#307]
When a user submits a post in a Moderated forum, the post goes into a queue for a moderator to review.
However, if the post has attachments, the moderator is unable to review the attachments, as there is a broken link.
The file is physically saved to a user directory:
..\Portals\0\Users\227\11\29411\myfile.jpg

But the post is displayed in the moderator queue with a direct link to the activeforums_Attach folder:
href="/Portals/0/activeforums_Attach/myfile.jpg"

Once the moderator approves the post the files does get moved to the activeforums_Attach folder and is properly viewable, but my users want to be able to check attachments before they approve them.

**Comment by supermansrf** [comment]
Marking as a confirmed bug.  I can't say that a solution will be made available soon, but I will make sure that it gets a look at sometime.  

@lfreer if you have someone figure this out, please pass it along and I will make sure the solution is built into future releases.

**Comment by artfuld** [comment]
This will be in the next release.
