### ISSUE TITLE
Missing ObjectQualifier in Activeforums_Reply_Save Stored Procedure

### ISSUE THREAD

**Issue by efficiondave** [ActiveForums/ActiveForums#312]
The are a couple versions of the activeforums_Reply_Save Stored Procedure that leave out the {databaseowner}{ObjectQualifier} in two lines... In the 06.02.06.SqlDataProvider, you can see it at lines 41 and 42. The table names need to be prefixed with "{databaseOwner}{objectQualifier}"

Without it, Quick Reply doesn't work on sites with an ObjectQualifier.

**Comment by artfuld** [comment]
Good catch, we changed this in 06.00.02 but not in 06.02.06. This will be fixed in the next release.
