### ISSUE TITLE
6.2.8 Feature settings Attachments losses it values after saving new values

### ISSUE THREAD

**Issue by Plumifrons** [ActiveForums/ActiveForums#314]
6.2.8 Feature settings Attachments losses it values after saving new values
![feature settings attachments](https://cloud.githubusercontent.com/assets/5980007/9446386/c140cbf6-4a91-11e5-8cee-4e1d749a9e18.png)

**Comment by supermansrf** [comment]
FYI I've had this issue for a long time.  I'm not saying its not a problem, just confirming that it isn't new.  I use a script to set these anyway.  Here is an example:

UPDATE activeforums_Settings 
SET 
  SettingValue =  'txt,tiff,pdf,xls,xlsx,doc,docx,ppt,pptx,jpg,png,gif'
WHERE (SettingName = 'ATTACHTYPEALLOWED') 
GO

**Comment by Plumifrons** [comment]
Yes I also used different scripts in the past. But in the last versions it worked okay and now the issue is back.

**Comment by artfuld** [comment]
There's some really strange things going on with the cache of the settings. Will try to look this over when I have the time.

**Comment by artfuld** [comment]
Checking this out, I'm getting some weird readings.
When I enter the Control Panel -> Forums the first forum or group that I click in can save without problem. But if I click on one forum/group and then change to another it doesn't seem like the form is updated with the values from that forum, or even if it looks like it's the right data showing that's far from what is being sent to the database when trying to save.

Can someone check if this works out? Just want to know if it's a local problem.

**Comment by supermansrf** [comment]
I've always had issues like this.  I had a forum that somehow lost something and we couldn't set anything on it until I manually reset some of the forum settings in the database.  

I have seen what you are talking about before.  I leave, head back out and come back in to set the second forum.  I also have a script that I keep handy to update the editor.  I have all my forums set to use Default DNN Editor.  Any time any security settings are changed on a forum, I have to run the script to set the editor again. 

This isn't a local problem.  There is something up with this.  I've gotten so used to it that I forgot it existed.

**Comment by artfuld** [comment]
I haven't seen this problem before, have noticed some times that the settings for text editor gets lost.

Is there any other settings that you know always get lost? I get the impression that it's only the modal-popups that forgets the data.

**Comment by Plumifrons** [comment]
I don’t know off other settings than Attachments and HTML Input that get lost.
I tested the last betas a lot with different max width and height settings and I thought that the setting problems where fixed. Until it appears again in 6.2.6 
So removed 6.2.6 and reinstalled 6.2.4 and until now the settings aren’t lost.

**Comment by artfuld** [comment]
Fixed with #413
