### ISSUE TITLE
6.2.8 Feature settings HTML input, not always all the fields are shown

### ISSUE THREAD

**Issue by Plumifrons** [ActiveForums/ActiveForums#315]
6.2.8 Feature settings HTML input, not always all the fields are shown.
![feature settings html input](https://cloud.githubusercontent.com/assets/5980007/9446479/3fde5168-4a92-11e5-9a25-68b33fc53ed5.png)

**Comment by artfuld** [comment]
Is there a pattern to when this occurs?

**Comment by artfuld** [comment]
Have you scrolled out to the far right to see if it just might be that the dropdowns are outside the browser?

**Comment by Plumifrons** [comment]
Not sure jet if there is a pattern. After the forum installation is starts okay but after a while it goes wrong. Maybe it goes wrong after I made a new forum group en forum. It doesn’t matter what browser I use and it also appears after a app pool recycle. It is not outside the browser.

**Comment by artfuld** [comment]
This is fixed with #413
