### ISSUE TITLE
6.2.8  Breadcrumb icons are not visible

### ISSUE THREAD

**Issue by Plumifrons** [ActiveForums/ActiveForums#316]
6.2.8  Breadcrumb icons are not visible.
![breadcrumb icons are not visible](https://cloud.githubusercontent.com/assets/5980007/9446519/7a605638-4a92-11e5-9eab-bd7b3d4391f5.png)

**Comment by ChrisHammond** [comment]
I installed 6.2.8 last night on sccaforums.com and these are working there. Are you using a Bootstrap skin? I'm using a version of my HammerFlex skin with Bootstrap 3.3.5

**Comment by Plumifrons** [comment]
I test with the standard DNN Gravity skin

**Comment by artfuld** [comment]
@Plumifrons seing your site I guess this is not a problem anymore, just reopen if it still is.
