### ISSUE TITLE
The forum doesn't appear, only the settings

### ISSUE THREAD

**Issue by JTSS** [ActiveForums/ActiveForums#320]
Hello,

I just instaled this module on DNN 7.0.6 but i don't see the forum, i even create one in the backoffice, it appears on backoffice but in the website page only appear the settings.

Here is a screenshot

Can you help me? I'm I missing a step?

Thank you.

![erro_forum_isal](https://cloud.githubusercontent.com/assets/14218740/9790068/dd3ecd16-57cb-11e5-9941-750a97c1dd61.jpg)

**Comment by artfuld** [comment]
Hello!

This should only be seen if you've added to module to a sub page of the user profile page.

**Comment by JTSS** [comment]
Thank you.

It was a thirth level page, now as a second level page it shows the forum.
