### ISSUE TITLE
I try to publish and notting happens

### ISSUE THREAD

**Issue by JTSS** [ActiveForums/ActiveForums#321]
Hello,

I try to post in the forum and notting happens. I tried with profile that has permissions for that and also with a host account.

I write the message, click in Submit and the page reloads. And I stay in the message editor.

No error appears on event viewer.

**Comment by artfuld** [comment]
Hello,
Need more info if you want help :).
What version of DNN and AF are you using? Is it a child portal?

**Comment by JTSS** [comment]
Hello.

Sure. Yes, its a child portal, and its runing DNN 7.0.6.

The AF I downloaded from the DNN store and the latest version there is 5.2.2

**Comment by artfuld** [comment]
As it is now i wouldn't use this module on a child portal. Everything using
a service (API) is broken.
There's a bug in dnn unfortunately.

You should really download the latest version from here. Lots if
improvements in af6
Den 11 sep 2015 5:08 em skrev "JTSS" <notifications@github.com>:

**Comment by JTSS** [comment]
Thank you for your help.

This version that is here, will work on a child portal?

I didn't find a instalation file for DNN. How can I install this version in DNN?

Thanks in advance

**Comment by supermansrf** [comment]
There are 2 downloads for each release. There is a source zip and an
installation zip. You want the install zip. Don't extract the zip
file. Use that to install.

I believe that the newer release will work on a child portal but there
will be issues. For sure. Definitely with attachments.
