### ISSUE TITLE
Calendar Opens at Bottom of Page

### ISSUE THREAD

**Issue by chandanray1983** [ActiveForums/ActiveForums#322]
In 6.2.8 version while creating new topic, when we click on the Announcement > StartDate/EndDate Calendars, it opens at the bottom of the page. Ideally it should open just beside the calendar icon. We tried in IE 9, Firefox 10 +, Chrome (Latest) and in all these browsers calendar opened at bottom of the page. See attached screen capture. Please provide any suggestions for the fixes.

![announcement_calendar](https://cloud.githubusercontent.com/assets/14235953/9854204/2bf4605e-5b25-11e5-83aa-bf7c03c7779f.jpg)

**Comment by johnhenley** [comment]
Thanks for reporting that.
It has been a bug forever.

John




On Mon, Sep 14, 2015 at 8:42 AM -0700, "chandanray1983" <notifications@github.com<mailto:notifications@github.com>> wrote:


In 6.2.8 version while creating new topic, when we click on the Announcement > StartDate/EndDate Calendars, it opens at the bottom of the page. Ideally it should open just beside the calendar icon. We tried in IE 9, Firefox 10 +, Chrome (Latest) and in all these browsers calendar opened at bottom of the page. See attached screen capture. Please provide any suggestions for the fixes.

[announcement_calendar]<https://cloud.githubusercontent.com/assets/14235953/9854204/2bf4605e-5b25-11e5-83aa-bf7c03c7779f.jpg>
