### ISSUE TITLE
Version 6.3 released

### ISSUE THREAD

**Issue by supermansrf** [ActiveForums/ActiveForums#335]
I have released version 6.3 as our first stable release in a very long time. 

Something to note, I just updated the PA to include one last pull to fix the issue where using localhost:port was causing issues with images.  If you downloaded 6.3 before 8:30 PM eastern on 10/21/2015 and need this feature, you should download a new version and do a repair install.  The version I released earlier today did not include this fix.  

Any questions or comments please let us know.

**Comment by supermansrf** [comment]
Sorry I forgot to mention that while this fix was important, I didn't want to release a new build number just to correct that one issue that so far seems to only have affected one person.  I'll save the next version for more changes

**Comment by robaxx** [comment]
I'm just checking this module for the first time since 4.x and it appears there are broken HTML tags in one or more templates. It causes the skin to break, especially if the container or skin pane is in a table cell. I think the errors are in ForumView.txt and possibly af_grid.ascx
