### ISSUE TITLE
Cleanup Build Process

### ISSUE THREAD

**Issue by ChrisHammond** [ActiveForums/ActiveForums#336]
Would anyone be opposed to be cleaning up the Build process for this module? I would like to modify the project/sln so that it uses the nuget package for MSBuild, should make it easier for people to work with.

If no one is opposed, I can make the changes and commit them in the next couple of weeks.

**Comment by mitchelsellers** [comment]
Build process uses a self-contained process, and NuGetPackages for most stuff.  It will build in an automated environment as of version 6.3.2
