### ISSUE TITLE
A split topic loses its attachment link

### ISSUE THREAD

**Issue by Plumifrons** [ActiveForums/ActiveForums#338]
AF 6.3.0

A split topic loses it's attachment link
![2015-10-29 20_28_02-test foto s vogels nederland 2015 - my website - forum - default - internet expl](https://cloud.githubusercontent.com/assets/5980007/10829805/7bf0d2c0-7e7c-11e5-87b1-33f8a46260bb.jpg)
![2015-10-29 20_29_41-gekraagde roodstaart - my website - forum - default group - - internet explorer](https://cloud.githubusercontent.com/assets/5980007/10829804/7bf064de-7e7c-11e5-82eb-b01fa6db5907.jpg)

**Comment by mitchelsellers** [comment]
This appears to be resolved with a prior release
