### ISSUE TITLE
Social Groups / Forum Mode / attachments / Authentication required

### ISSUE THREAD

**Issue by gregclemens** [ActiveForums/ActiveForums#341]
I'm utilizing the Social Groups module on my site and using the AF module on each group's page.  In the Forum setting for AF I'm choosing the "Social Groups" mode.  When I try to attach a document to a post it shows the document load to 100% then I get a Login pop-up saying "Authentication Required".  I'm already logged in though.  I then cancel and then get a "A server error has occurred" message.  There's nothing in the event viewer though.

**Comment by sleupold** [comment]
please check permission for the target folder in Admin > File Management.
Also make sure, the size limit and site disk quote is not reached.

**Comment by gregclemens** [comment]
sebastian, how do I check the permission in Admin > File Management?  I see the folder but it's empty.

**Comment by deskpal** [comment]
Hi Sebastian,

We have been trying to assist Greg with this problem and the problem can be reproduced by creating a child portal an adding Active Forum to a page on the child portal. Then if you try to post and attach a file you will see the Authorization message or just {"Message":"Not Authorized"} if you use fiddler.

Thanks,
Aderson

**Comment by artfuld** [comment]
Unfortunately child portals work really really bad atm, AF doesn't get the correct ID from DNN of the logged in user.
I would not recommend using AF on a child portal.

**Comment by sleupold** [comment]
Thanks for the feedback, Aderson, thís sounds like a cookie issue or the site is not properly identified from portal alias. 
I am not aware that this is a general issue with DNN, it might be caused by issues retrieving forum path. Are you using AF URL rewrite?

**Comment by deskpal** [comment]
Thanks Sebastian and Joakim. 

@sleupold  - > We have just reproduced the exact same behavior on a fresh new DNN 7.4.2 install. 

1 - Put up a DNN 7.4.2 test site;
2 - Installed Active Forums 6.3;
3 - Created a child portal;
4 - Added Active forums to a page on that child portal and tried to attach a file to a post. That is when we saw the same issue as on Greg's site.

In terms of URL rewrite, we haven't done any special setup for that. What we did was exactly what I have described on the above 4 steps.

Thank you,
Aderson

**Comment by artfuld** [comment]
If you continue with AF on a child portal you will notice that even basic security as who sees what forum doesn't work. If I recall correctly, when AF asks DNN for the ID of the logged in user it returns null or 0.
Please don't use it on child portals till someone has fixed the problem :/.

**Comment by deskpal** [comment]
Understood @artfuld . Thank you!

**Comment by sleupold** [comment]
Hi @deskpal, this sounds like AF is not using PortalID from module context. It is obviously an issue of the module, as this bug has not been reported for other modules as well.

**Comment by deskpal** [comment]
Thank you @sleupold . It seems all else on the module works fine in child portals except the file attachment.

**Comment by gregclemens** [comment]
@mitchelsellers should I assume this won't be fixed and that's why it's being closed?

**Comment by gregclemens** [comment]
@mitchelsellers I understand.  Can you tell me which related ticket you didn't delete so I can follow?  I couldn't find it.  Thanks.

**Comment by mitchelsellers** [comment]
Actually, I just created a new one #392 to track this in detail
