### ISSUE TITLE
Active forums error on site move to new host

### ISSUE THREAD

**Issue by ROIAF** [ActiveForums/ActiveForums#343]
After moving a working DNN installation to a new host, we see this when we try to load the site:

[NullReferenceException: Object reference not set to an instance of an object.]
   DotNetNuke.Modules.ActiveForums.ForumsReWriter.OnBeginRequest(Object s, EventArgs e) +2348
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +136
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +69

Any suggestions?

**Comment by supermansrf** [comment]
Go edit web.config and look for the AF rewriter and comment it out.
Then restart your app pool.

I'm on the road. If you need better instructions let me know and I'll
send them later tonight.

**Comment by monty241** [comment]
Hello, I have exactly the same error. After disabling the AF rewriter it is gone, but the cause is still there.
What is recommended approach?

**Comment by mitchelsellers** [comment]
This issue can happen is using the site on a temporary URL that isn't listed as a Portal in the PortalSettings table.
