### ISSUE TITLE
DNN 8.0 Beta Update References for Telerik

### ISSUE THREAD

**Issue by thabaum** [ActiveForums/ActiveForums#345]
Telerik references need updated or the controls are not found.  Can you release a DNN 8.0 beta release so we can debug this version for when the new update comes out?  The Telerik controls are now 3rd party controls from what I understand and will be phased out of the DNN installations.  Cannot go to edit the module in DNN 8.0 as of now.  If we can get an 8.0 version release we can begin testing it on the RC.

**Comment by bvillersjr** [comment]
Is this project still alive?

**Comment by supermansrf** [comment]
Yes absolutely.  However we aren't actively pursuing DNN 8+ just yet.  Waiting on some other major developments to get done before trying to worry about DNN 8 issues.

**Comment by mitchelsellers** [comment]
This was addressed with the 6.3.2 release
