### ISSUE TITLE
Restrict sending Messages for specific users or for a user role.

### ISSUE THREAD

**Issue by maduranga001** [ActiveForums/ActiveForums#346]
Hello,

I need to restrict messaging feature for some users. I restrict the access permission of the messages page for those users. But still those users can send messages thruogh the forum posts messages icon.
How can we restrct this in the forum too? Please can you advise?

Thank You!

**Comment by artfuld** [comment]
Hey @maduranga001 
Unfortunately there's no way to restrict this from what I can see. It would be nice if DNN hade a way of disabling the messaging for a group.

Don't know about the next version of AF but it would be fairly easy to create a new token for profiletemplates, something like this.
[AF:AllowedRoles:Administrators;EmailGroup;MyBFFs][AF:PROFILE:PMLINK][/AF:AllowedRoles]
and even the other way around with DeniedRoles.

Or if someone had more time on their hands it could be a setting for the forum where you get to pick what group can see the PMLink.

But for now, no there's no way to do that (from what I can see)

**Comment by maduranga001** [comment]
Thank you for your reply dear.

It it is possible, please can you add this feature to the wishlist? I belive this would be a good feature. So this can apply for any content part for any user role in the template then.

Thank You!
