### ISSUE TITLE
DNN8 AF6.3.0 clicking My settings gives an error page.

### ISSUE THREAD

**Issue by artfuld** [ActiveForums/ActiveForums#347]
![image](https://cloud.githubusercontent.com/assets/6116748/12351133/b0a2bd44-bb7b-11e5-962c-faae7e8f176b.png)

**Comment by nunotv** [comment]
I have the same problem. Do you have any update?
best regards
ntv

**Comment by sleupold** [comment]
it works for me (AD 6.3.0 on DNN 7.4.2 with Advanced URLs enabled), anything special in your install?

**Comment by artfuld** [comment]
@sleupold this is in DNN8
Just posting problems so that when we start to tackle the upgrade to dnn8 we have them writte down :).

**Comment by mitchelsellers** [comment]
Closing as a duplicate
