### ISSUE TITLE
Cancel Subscribed threads for other users

### ISSUE THREAD

**Issue by maduranga001** [ActiveForums/ActiveForums#350]
Hello,

Some users have subscribed some threads. But we have unauthorised user registration for a few users from the forum website. 
A) So are they still receiving the emails for the subscribed threads? 
B) Can admins cancel their subscriotions and how can we do this? 

Pleae can you advise? I think if the admin limited/unauthorised their access then the users shouldn't receive the notifications and all forum access.

Thank You!

**Comment by supermansrf** [comment]
I believe that you have to remove the subscribers role to prevent subscription emails from being sent. Unauthorizing isn't enough.

**Comment by maduranga001** [comment]
Thank you for the reply.

Please, can you tell me how to do this?
This is something like this. If a user click the checkbox for a thread or for a forum category to "Subscribed to receive emails", and when we unautorised that user from the system user regsitration, still he can receive it? All registered users have this feature to subscribe for any thread.

Is there a feature to see, who are subscribed for threds or forums? 

Pleas cn you advise?

**Comment by supermansrf** [comment]
This is a feature that I would like to see happen. Where admin can see who is subscribed and maintain subscriptions. 


Currently the only way I know of is via the admin user management. Where roles are assigned and removed and remove the subscribers role. 

Alternatively you can assign permissions for roles to not be able to subscribe per forum or group too. This is in control panel under each forum or group permissions.

**Comment by maduranga001** [comment]
There are no any user role assigned to these users. Only registered members by default. But I made it Unautorised. Is this enough to stop the receiving subscribed threads coments to the emails?

Appreciete if you can add this feature to the wishlist. (Admins to see the subscriptions of users) 
So we have a hope to see this in the future.

Thank You!

**Comment by sleupold** [comment]
AF will stop sending users, once his account has been removed (not just marked as deleted)

**Comment by maduranga001** [comment]
Thank you for your answer, Sebastian.
For some reasons, We can not delete/remove users and just need to change only the user role or just make them UnAutorised temperary. 
Once we make them UnAutorised, Then we need to stop sending notifications until we make them as an Authorised user.

**Comment by sleupold** [comment]
Manduranga, you may alter the stored procedure retrieving the notifications, however, this will have an impact on performance
