### ISSUE TITLE
Font change

### ISSUE THREAD

**Issue by JohnnyLoki** [ActiveForums/ActiveForums#351]
Hey guys I'm trying to change the font of the afpostbody but I can't seem to be able to find what I should do, I tried adding some lines of code in the TopicView but didn't work any ideas? 

For the post body it's using New Times Roman and I would like to change it to Arial as is the whole site.

**Comment by ChrisHammond** [comment]
Just add custom CSS  for afpostbody to your Skin.css file, OR add it to Portal.css (accessible through the admin/site settings page)

Example
.afposttopic .afpostbody, .afpostreply1 .afpostbody, .afpostreply2 .afpostbody {
    font-family: fantasy;
}

**Comment by JohnnyLoki** [comment]
cool thanks mate
