### ISSUE TITLE
Getting Issue on Active Forums when I try to use it with Social Module

### ISSUE THREAD

**Issue by patilsandiip** [ActiveForums/ActiveForums#355]
Active Forums Version - 06.03.00
I am receiving following error when I try to use it with 
Error: Active Forums is currently unavailable. DotNetNuke.Services.Exceptions.ModuleLoadException: Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object. at DotNetNuke.Modules.ActiveForums.Classic.GetControl(String view, String options) --- End of inner exception stack trace ---

Thanks,
Sandeep

**Comment by sleupold** [comment]
which module do you try to combine?
