### ISSUE TITLE
not receiving any notification emails from AF (any version) in DNN 7.4.2

### ISSUE THREAD

**Issue by DylanTusler** [ActiveForums/ActiveForums#356]
I've been grappling with this for months, without being able to work out what's going on. I'm a module developer, been working with two main DNN sites using ActiveForums, and I've stopped receiving notification emails from both of them.

I've been through previous threads on this and it has not helped. I've spent literally months tearing my hair out on this issue.

I've upgraded both sites from earlier (5.x) versions of AF to 6.3.0, and the situation has not changed.

1) DNN generally is working absolutely fine for sending emails.
2) This is affecting two different sites, one in Azure, one with a hosting provider. Both are affected the same.
3) If I create a new user account and login with that account and subscribe to a forum, I don't get notifications.
4) Existing users who had notifications switched on prior to all this happening, still get notifications fine!
5) I get no errors in the event log of any kind.
6) This all started when I tried to switch on auto subscriptions for a forum. As soon as I turned that on, notifications ceased. That's the only thing I can peg to that point in time.

Any advice, tables to look at, anything that could assist would be gratefully received.

**Comment by sleupold** [comment]
I'd check content of database table activeforums_Subscriptions

**Comment by sleupold** [comment]
we are using AF with DNN 7.4.2 and don't have issues receiving notifications.
The site is configured to use SMTP configuration from Host Settings.

**Comment by DylanTusler** [comment]
This is resolved. I think the main problem was interference in my inbox from an email management tool called unroll.me
