### ISSUE TITLE
Add image to DNNConnect.CKE editor gives not supported message

### ISSUE THREAD

**Issue by Plumifrons** [ActiveForums/ActiveForums#357]
AF 6.3

When using the DNNConnect.CKE provider it is not possible to add image to the editor. It gives a  not supported message.

![addpicturetoeditor](https://cloud.githubusercontent.com/assets/5980007/12845708/1f824864-cc08-11e5-8f1f-5aa9540987f5.jpg)

**Comment by artfuld** [comment]
Is this still a problem @Plumifrons? I can't reproduce it

**Comment by Plumifrons** [comment]
I don’t use the DNNConnect.CKE anymore but on my test site it is working now.
