### ISSUE TITLE
Uploading Attachments Requires Server Authentication?

### ISSUE THREAD

**Issue by joannschlosser** [ActiveForums/ActiveForums#360]
![capture](https://cloud.githubusercontent.com/assets/17364782/13199812/99705174-d7fd-11e5-80e8-e73bee27d33b.jpg)

I don't have to do this when I am setting up the site within DNN itself.  Where is this configured?

I also noticed that only the host user can even get to this point.  A regular user doesn't have the attachments option at all even though it is enabled on the Features tab.

**Comment by supermansrf** [comment]
Are you still trying with AF 5.2.0? I remember this issue. I believe it was fixed in later releases. What version DNN and AF are you using?

**Comment by joannschlosser** [comment]
DNN7 and AF 6.3.  Thanks!


-------- Original Message --------
Subject: Re: [ActiveForums] Uploading Attachments Requires Server
Authentication? (#360)

**Comment by joannschlosser** [comment]
Dnn 7 and AF 6.3  Thanks.

**Comment by joannschlosser** [comment]
I have AF 6.3 and DNN8 on my local machine and I can upload an attachment, but since I don't have the HTML editor interface, I can't add them inline.  Where does that get turned on and off?  I will keep looking.  Thanks.

**Comment by joannschlosser** [comment]
Not logged in as an admin, yet when I try to insert an image into a post, it wants me to pick an existing image from and existing folder or upload a new image to one of them.  That can't be right.  I did notice that on the DNNSoftware site's forum but made sure to make my own folder for uploads there.  But that is just me.  Is there some configuration setting I am missing?

**Comment by sleupold** [comment]
Do you experience the same issue in HTML module when uploading an image?
