### ISSUE TITLE
Adding AddThis to Posts

### ISSUE THREAD

**Issue by joannschlosser** [ActiveForums/ActiveForums#361]
Reading older materials stating to add AddThis to the AddThis integration section of the Control Panel.  I don't see it.  Where do we put this?  

I see a reference to it in the code for the template.  Not sure what to do with it.  I could change it from 0 to 1 but would probably need to put the AddThis account info somewhere.

![capture](https://cloud.githubusercontent.com/assets/17364782/13200901/ca605e9c-d829-11e5-93c2-5b0edff0d52f.jpg)

Thanks.

**Comment by mitchelsellers** [comment]
Looking at the implementation of this you would use [AF:CONTROL:AddThis:USERNAME].  However, I am not sure if the current release version is going to be proper for use with AddThis.

You could do this with a standard Add This Integration though, inside of the same template.
