### ISSUE TITLE
Migrating from PHPBB

### ISSUE THREAD

**Issue by joannschlosser** [ActiveForums/ActiveForums#362]
Our club's entire website is a PHPBB forum with a few static pages attached.  Anything actually doing anything is done through bits and pieces of functionality on other websites which makes it hard to keep anything in sync.  I am moving the whole ball of wax over to DNN over the course of the next year.  I have a recent copy of the data and the attachment files here locally now and am ready to do the conversion.  Not that bad on the surface (OK, PHPBB doesn't record enough to create user accounts, but I should have the info that goes with the email addresses sometime today) but it would be nice if there were conversion scripts already available for sale or to share.  If not, I will share what I come up with but if I don't have to reinvent the wheel, that would be just super duper.

**Comment by sleupold** [comment]
sounds like a great contribution

**Comment by artfuld** [comment]
Hello @joannschlosser how is this going?
There have been several discussions about moving forums one way or another. What I've come in peace with is that it is more or less only possible to do a conversion inside the same dnn-site.

Please read the following threads #264 and #254 to get some ideas and steps what to do.

My 2 cents in this matter is to copy over the users if possible and start the forum on a clean slate.

**Comment by joannschlosser** [comment]
I have been sidelined doing other things but had it almost completed with the exception of some clean up like dealing with inline images and emojis.  - not bad
![capture 1](https://cloud.githubusercontent.com/assets/17364782/14397167/d9093c98-fda9-11e5-8a83-002c86702e4f.JPG)

**Comment by artfuld** [comment]
Really nice! GJ!

**Comment by mitchelsellers** [comment]
Closing this ticket for the moment.  Would look at accepting a pull request for contributions for a migration script.
