### ISSUE TITLE
File Type Not Allowed

### ISSUE THREAD

**Issue by joannschlosser** [ActiveForums/ActiveForums#363]
I have the same file types and sizes for all forums and they are all set to attachments allowed. The allowed file string is
jpg,gif,pdf,doc,docx,xls,xlsx,png 
max size is 2000000 (2MB) 
 max dimensions are 800x800

But I cannot upload a 29KB, 300x600 jpg file. 
Is there a syntax problem with the file types or something else I am missing?
Thanks.

PS I am very close to having a set of scripts to import PHPBB into AF.

**Comment by sleupold** [comment]
does the file have proper extension  (.jpg instead of .jpeg)?

**Comment by joannschlosser** [comment]
Both jpg and jpeg are in my allowed file types.  I did eventually scrap the whole thing and start over and got it to go.  I am sure it was a configuration issue somewhere along the way.  Thanks for following up.
