### ISSUE TITLE
DNN 8.0 and Active Forum Issues

### ISSUE THREAD

**Issue by thabaum** [ActiveForums/ActiveForums#364]
Issues with Active Forums and DNN 8.0

Breaking changes in DNN 8 makes Active Forums unusable.
1.  Cannot Access Forum Control Panel
2.  Pages with URL SEO wont work anymore (  domain.com/Forums/aft/8 links work but if it has a name to SEO the page domain.com/forums/general-discussions the page is not found)  No way to access the CP so you cannot change this easily to point to normal links.
3.  Module Settings wont load.
4.  What's New module uses the normal links instead of the forum page name as well.  It allows you to access the forum post but when you post a reply it goes to page not found.  The reply is however posted when you click back to the forum thread.  

Anything else I am forgetting?

**Comment by Roylej** [comment]
Didn't realise there was an issue with DNN8. We just built a new portal and discovered these issues. Gives us a bit of a problem. Might need to go back to v7.

**Comment by eddycrompton** [comment]
Additional:
Creating a new Forum or Group leaves users with spinning progress wheel. Note that it does actually create the Group / Forum successfully.

**Comment by byte-artisan** [comment]
i got 404 error on every links running a dnn 8.0.2 installation. Probably has to due to multi-language. Doesn't happen on single language sites on the same dnn installation.

**Comment by Plumifrons** [comment]
Does restart the app pool help?

**Comment by byte-artisan** [comment]
nope. Control panel links end all in 404 error.
A note: the error is only show in event log.

**Comment by frozendnn** [comment]
Is anyone using AF on DNN 8 ?

**Comment by eddycrompton** [comment]
From speaking to developers who have worked on this module, it will need some work before it's ready for DNN8.
We opted for YAF for another client, but have used AF for many years and would prefer to use that, but too risky at the moment.

**Comment by frozendnn** [comment]
I think this is the end of AF. Mitchel Sellers is a busy man. He is not going to do it.

**Comment by mitchelsellers** [comment]
@frozendnn We are working on this.  At this point it is a community contribution that is taking a lot of time to get right.  I'm trying to dedicate time to this each week to continue the progress that we have been making internally, but, sadly we have to handle committed, paid work first.

If there are any developers that would like to HELP with this effort I'd love to have others assist.

**Comment by wmorgenweck** [comment]
I was able to make the latest release compatible with DNN 8 in less than an hour. Is that what people are looking for or are there other issues to address?  I did spend sometime playing with it. There are quite a few UI/UX issues that seem to have been introduced over the past few years, but overall it seems to be working fine. 

Thanks,
Will

**Comment by artfuld** [comment]
@wmorgenweck just getting it to work on dnn8 would probably suffice for 98% of the users. Perhaps you could up that and @mitchelsellers can work from there with what he's doing?

**Comment by artfuld** [comment]
This is the list @mitchelsellers is working to fix according to another thread

1.) Full DNN 8.x support
2.) Fix any performance issues possible
3.) Integration of Tapatalk

**Comment by thabaum** [comment]
It would be nice to have a DNN 8 package first...

**Comment by mitchelsellers** [comment]
Will,

If you have a interim fix that would be great. My work this far is on some performance stuff. If there is a quick fix I'd like to get a release out as soon as we can.

On Jul 16, 2016, at 2:43 PM, Cody <notifications@github.com<mailto:notifications@github.com>> wrote:


It would be nice to have a DNN 8 package first...

-

**Comment by frozendnn** [comment]
@wmorgenweck, you surprised me there, my old friend. If you can share your DNN 8 compatible code, that would be most appreciated. @mitchelsellers, ( and others) can then work on other things, as he (they) finds time.  Unfortunately, I am useless in such matters.

**Comment by mitchelsellers** [comment]
Just released a beta with these fixes.  Will continue testing

**Comment by Roylej** [comment]
Great stuff Mitch.

**Comment by mitchelsellers** [comment]
Issues resolved with Version 6.3.2
