### ISSUE TITLE
New update in the works

### ISSUE THREAD

**Issue by supermansrf** [ActiveForums/ActiveForums#365]
I wanted to let everyone know some important news.  Several of the organizations I represent have determined that not having a very well oiled tapatalk integration is a severe crutch to their day to day operations.  We have a few sites with thousands of active daily users of AF.  While the new responsive layout is nice, it is still very cumbersome to navigate on a mobile device.  

When we had tapatalk working properly, things were much better.  However the daily crashing and other random issues we had was not acceptable.  I have been looking into the best way to do this moving forward and have finally come up with a plan and assigned the project.  

Mitchell Sellers has won the project and will be providing his services to implement Tapatalk into AF.  I have decided that building it directly into AF is going to be the best option.  This does not mean that tapatalk will be forced on anyone, you will have the option to use it or not use it.  But it does mean a much cleaner implementation and better tapatalk features.  I am funding this project through several of my clients who want to see this happen.  

We have a long way to go.  This is just at the beginning stages of development (I haven't even mailed out a check yet - but will be doing so the beginning of this week).  And once they do get started we expect it to take a minimum of 4-6 weeks.  But I believe that it will be time and money well spent.  

Those of you who don't know Mitchell and his crew (Iowa Computer Gurus), they have been instrumental in many DNN developments over the years and I believe are probably the best in the business.  I'm honestly very grateful that he was up to taking on the project and I know that he will be doing a bang up job on this.  

As soon we have gotten past this hurdle, tackling other things like DNN 8+ and other things will be on the radar.  

Once they start on their side of things, I will not be allowing any pulls until the project is done.  I do not want to burden them with anything more than their job.  After it is done we can get back to business.  I have been very limited on time lately and haven't had much time to devote to AF.  When this is done I can see things getting back on track.

**Comment by Plumifrons** [comment]
That’s great news. Looking forward to see the new tapatalk.

**Comment by gitmoregrits** [comment]
Seth, this is great news!  Mitchel Sellers and Iowa Computer Gurus have a great reputation.  Having ICG involved in this project should drive very nice results.

I don't know if it's fair game for the overall Tapatalk integration or not but one thing I would love to see is richer overall user profiles including the user transition of such from AF <>DNN.  Scenario:  Right mouse on a given user from AF and have a selection to view their profile and then easily come back to AF.  And what about Private Messaging via Tapatalk --might we get some nice AF integration here too? :)

**Comment by sleupold** [comment]
due to security issues in DNN 7, which are currently fixed in DNN 8.0.1 only, please consider a new release that works with DNN 8, thanks.

**Comment by thabaum** [comment]
^^ ++

**Comment by artfuld** [comment]
Sounds really good @supermansrf 
:+1:

**Comment by mitchelsellers** [comment]
Closing this for a later ticket for new direction
