### ISSUE TITLE
Delete button on Notification page not working for moderators

### ISSUE THREAD

**Issue by tdarr** [ActiveForums/ActiveForums#366]
When an alert has been placed on a reply and the moderator navigates to the notification page and clicks delete, an error with a yellow background appears and the reply is not deleted.  Same for the ignore button.  I'm using DNN v7.2.1 and active forums v5.1.4.

**Comment by mitchelsellers** [comment]
This was fixed in an early 6.x version of Active Forums.  Recommended upgrade to latest supported version for your platform.
