### ISSUE TITLE
DNN 7.1.2 and AF 6.3.0 not receiving email notifications

### ISSUE THREAD

**Issue by welchwebdesign** [ActiveForums/ActiveForums#367]
I am using DNN 7.1.2 and AF 6.3.0 and I do not receive any email notifications.  No event viewer messages.

**Comment by sleupold** [comment]
did you make sure, the AF Scheduler Job is enabled (in Host > Schedule) ?

**Comment by OnyakTech** [comment]
I had the same issue and solve it by replacing the entire "SendNotification" method online 220 in the Email.cs with the line below.  It appears to be an issue for people that require SSL connections to their email servers.

DotNetNuke.Services.Mail.Mail.SendMail(fromEmail, toEmail, "", subject, bodyHTML,"", "html", "", "", "", "");

**Comment by Joezyz** [comment]
Where is the Email.cs file?  I have searched and I cannot find it?

**Comment by sleupold** [comment]
email.cs is part of DNN Platform source code

**Comment by Joezyz** [comment]
Thanks Sebastian,  So I would have to rebuild DNN to put Chris' fix in.
I am having the same issue, that none of posts are being sent via email.  They are put in the activity feed, but not being sent out to the email account.

**Comment by sleupold** [comment]
if you are running same version, yes
I have no issues with notification in AF 6.3.0 on DNN 7.4.2

**Comment by ChrisOnyak** [comment]
The Email.cs file is in the Active Forums source, located in the "class" folder.  You will need to compile the changes.   My suggested change isn't the best solution, but it is a very quick fix to solve the issue with email providers that require SSL.

**Comment by sleupold** [comment]
Thanks for the clarification, [~chrisonyak].
Obviously, AF is bypassing DNN email classes and just obtaining SMTP Settings from Host Settings (ignoring site specific Settings, which were introduced in DNN 7.3, AFAIR) -  not best practice. The reason might be using different templates for HTML and plain text in MIME part in a single HTML email.

**Comment by ChrisOnyak** [comment]
I agree that the solution I proposed is not the best solution (which is why I am not contributing the code change directly), however it is a quick patch that solves the problem without compromising features.  The site settings and templates will still be used, the change simply lets DNN handle the email processing.  

There email handling in AF does not properly handle an SSL connection to the email server, while DNN does.

**Comment by mitchelsellers** [comment]
Separate issue has been tracked for resolution of email distrbution issues with Active Forums.  Closing this duplicate ticket.
