### ISSUE TITLE
Cannot add reply to topic

### ISSUE THREAD

**Issue by JeddJones1** [ActiveForums/ActiveForums#368]
Administrators can add replies to topics successfully. However, when a user we have setup with general View/Read/Create/Reply/Edit/Delete security access levels attempts to submit a reply, the user is redirected back to the main forum page and the new post is not added. Two errors are logged in the event viewer when this occurs. 

1. 

DotNetNuke.Services.Exceptions.PageLoadException: The Controls collection cannot be modified because the control contains code blocks (i.e. <% ... %>). ---> System.Web.HttpException: The Controls collection cannot be modified because the control contains code blocks (i.e. <% ... %>). at System.Web.UI.ControlCollection.Add(Control child) at DotNetNuke.Services.Exceptions.Exceptions.ProcessModuleLoadException(String FriendlyMessage, Control ctrl, Exception exc, Boolean DisplayErrorMessage) 

2.

DotNetNuke.Services.Exceptions.ModuleLoadException: Maximum Recipient Limit Reached. To send the message, please remove some recipients from the To List. ---> DotNetNuke.Services.Social.Messaging.Exceptions.RecipientLimitExceededException: Maximum Recipient Limit Reached. To send the message, please remove some recipients from the To List. at DotNetNuke.Services.Social.Notifications.NotificationsControllerImpl.SendNotification(Notification notification, Int32 portalId, IList`1 roles, IList`1 users) at DotNetNuke.Modules.ActiveForums.af_quickreplyform.SaveQuickReply() at DotNetNuke.Modules.ActiveForums.af_quickreplyform.OnLoad(EventArgs e) 

DNN Version: 07.01.00
Active Forums Version: 5.2.2

Can someone please assist? 

Thank you!
Jedd

**Comment by artfuld** [comment]
Is this a new install? You should upgrade to the latest version of AF

**Comment by artfuld** [comment]
I'm guessing that you got the installpackage from codeplex, unfortunately that's a really old version (March 12, 2014).
You can find the latest version here.
https://github.com/ActiveForums/ActiveForums/releases/tag/v06.03.00

**Comment by JeddJones1** [comment]
I've upgraded to the latest version that you linked in above, but we are still getting the same two error messages as before.

**Comment by artfuld** [comment]
Is this a child portal?

**Comment by JeddJones1** [comment]
It is the only portal currently there on the install. It is portal id 5. Not sure if being anything other than portal id 0 classifies it as a child portal or not. Portal setup (screen capture) is attached.
![capture](https://cloud.githubusercontent.com/assets/18333667/14503650/a7311e2c-0176-11e6-8184-b185f3b356f5.JPG)

**Comment by artfuld** [comment]
No that is a parent-portal, a child-portal would be something like www.lencore.com/yourSite.

Is there any data in the forum yet? Is it possible to uninstall and do a clean install with AF6.3?

**Comment by JeddJones1** [comment]
That seems to have resolved the problem. One thing I noticed (only after doing a clean install) is that the admin had removed the "All Users" user role from the security settings. I'm guessing that would cause all sorts of problems, but not sure if that was the actual issue or not here.

**Comment by artfuld** [comment]
That shouldn't cause any problem at all, only the desired effect :).
