### ISSUE TITLE
Version 8 Support, Performance & Next Release

### ISSUE THREAD

**Issue by mitchelsellers** [ActiveForums/ActiveForums#369]
Everyone,

This is the simplest route for me to get something out, so I will go ahead and post it here.  As Seth mentioned before I am working on the next release.  I've found a number of performance issues that I am also working on, but looking to identify any and all items that people see as outstanding.

For this release, my goals are as follows.

1.) Full DNN 8.x support
2.) Fix any performance issues possible
3.) Integration of Tapatalk

If you have an outstanding issue, please make sure to get it posted.  Also, if you are willing to help test, or otherwise please let me know.  This release is going to be far larger than I expected, but we have to do it the RIGHT way and not just throw a release out there.

**Comment by Plumifrons** [comment]
Looking forward to see the new release. I can help testing, just let me know what I can do.

**Comment by thabaum** [comment]
You rock!  I would love to help with testing as well if needed.

**Comment by thabaum** [comment]
any idea when there may be a beta release?

**Comment by mitchelsellers** [comment]
I am hoping for a beta/alpha release within the next 1-2 weeks.  Been crazy wrapping my head around all of the open issues, upgrade issues, and API changes.

**Comment by artfuld** [comment]
@mitchelsellers how is this going, do you need any help testing or anything else?

**Comment by patilsandiip** [comment]
Hi,
When you think new version will get released?

**Comment by supermansrf** [comment]
I spoke briefly with Mitchell the week before last.  There have been several interruptions as well as unforeseen challenges trying to get out the next update.  We really don't have an ETA right now but will let everyone know as soon as we get something to test.  I would expect a beta release within several weeks but we aren't going to release anything until its something worth testing.  Sorry this isn't much information but know that it is definitely in progress.

**Comment by artfuld** [comment]
Any news is better than no news :)

Thanks for the update Seth, just let us know if there's anything we can do to help.

**Comment by mitchelsellers** [comment]
Closing this issue, as DNN 8.x support is here.

Pruning the listing of issues to create a realistic expectation of a next release
