### ISSUE TITLE
Announcements

### ISSUE THREAD

**Issue by GotVerve** [ActiveForums/ActiveForums#37]
Announcements fails.
We are trying to use Active forums in Evoq Social version 1.2.0.421. 
When we try to set announcements in additional options for a topic it will save but then send you back to the forum view page. When ever you click on the topic it does the same and sends you back to the forum page.

Any ideas or feedback would be helpful.

Thanks.
##

**Comment by artfuld** [comment]
I can not reproduce this, is this still a problem?
