### ISSUE TITLE
Please do not change the anonymous posting feature

### ISSUE THREAD

**Issue by frozendnn** [ActiveForums/ActiveForums#370]
I see there are lots of changes/updates in process. I use ActiveForums only because it allows anonymous (not signed or logged in) users to participate in the forum conversation. This feature is very important (for me) so please please do not change that. Thank you very much. 

Also, if you can, there was a change made some time back....instead of displaying the user's temporary username in some templates (Active Topics, Topics Template) the forum displays "Anonymous User." Can that be fixed?

**Comment by mitchelsellers** [comment]
There is no desire to remove this functionality, the username template issue is addressed in another ticket.
