### ISSUE TITLE
System.IndexOutOfRangeException: Cannot find table 0. Exception

### ISSUE THREAD

**Issue by lveeramani** [ActiveForums/ActiveForums#371]
System.IndexOutOfRangeException: Cannot find table 0. at System.Data.DataTableCollection.get_Item(Int32 index) at DotNetNuke.Modules.ActiveForums.ForumController.GetForumView(Int32 portalId, Int32 moduleId, Int32 currentUserId, Boolean isSuperUser, String forumIds) at DotNetNuke.Modules.ActiveForums.Controls.ForumView.BuildForumView(Int32 ForumTemplateId, Int32 CurrentUserId, String ThemePath

**Comment by artfuld** [comment]
Hello @lveeramani,
What version of AF and DNN are you using?
Is it a fresh installation?
If not, what happened that caused this?

**Comment by lveeramani** [comment]
Hi,
I am using AF 6.2.5 and DNN 7.03.04.
No.
I will crash the page.

**Comment by frozendnn** [comment]
Happens to me too.

**Comment by artfuld** [comment]
Is your forums at a total stop now or is this error coming and going? When does it happen? Have you changed anything else in DNN before this started? Any new modules in DNN?
Not sure if this is it but I had a similar problem where I had to create a new forum directly in the db, will have a look around to see if I can find the code for that.

**Comment by artfuld** [comment]
My bad, the problem I had was with missing a portal with ID 0, so it shouldn't have anything to do with this.
If you give me a copy of your dnn-installation together with the DB and a SU-login I can debug this for you.

**Comment by mitchelsellers** [comment]
There were a few issues with the SQL scripts in those version, upgrading to 6.3.2 should resolve this issue.
