### ISSUE TITLE
unable to add new topic

### ISSUE THREAD

**Issue by schwall2000** [ActiveForums/ActiveForums#372]
Hello everybody,

I have a strange problem with AF :
DNN 070304
Active Forum 0630

Everything went fine for 3 weeks .... and suddenly I can´t create new topics .... the mask appears ... I can add everything and once  I want to send the topic I just stay on the input mask (its a reload). ... no error message .... no message in the event log ....

editing existing entries is ok
responding also

Does somebody has any idea??
Greetings from Bonn

**Comment by mitchelsellers** [comment]
Closing this issue due to age.  Was not able to recreate issue with current release.
