### ISSUE TITLE
DNN Settings returns the following error in 6.3

### ISSUE THREAD

**Issue by rossmick** [ActiveForums/ActiveForums#374]
Error: is currently unavailable. DotNetNuke.Services.Exceptions.ModuleLoadException: Unknown server tag 'dnn:DnnNumericTextBox'. ---> System.Web.HttpParseException: Unknown server tag 'dnn:DnnNumericTextBox'. ---> System.Web.HttpParseException: Unknown server tag 'dnn:DnnNumericTextBox'. ---> System.Web.HttpException: Unknown server tag 'dnn:DnnNumericTextBox'. at System.Web.UI.TagPrefixTagNameToTypeMapper.System.Web.UI.ITagNameToTypeMapper.GetControlType(String tagName, IDictionary attribs) at System.Web.UI.MainTagNameToTypeMapper.GetControlType2(String tagName, IDictionary attribs, Boolean fAllowHtmlTags) at System.Web.UI.MainTagNameToTypeMapper.GetControlType(String tagName, IDictionary attribs, Boolean fAllowHtmlTags) at System.Web.UI.RootBuilder.GetChildControlType(String tagName, IDictionary attribs) at System.Web.UI.ControlBuilder.CreateChildBuilder(String filter, String tagName, IDictionary attribs, TemplateParser parser, ControlBuilder parentBuilder, String id, Int32 line, VirtualPath virtualPath, Type& childType, Boolean defaultProperty) at System.Web.UI.TemplateParser.ProcessBeginTag(Match match, String inputText) at System.Web.UI.TemplateParser.ParseStringInternal(String text, Encoding fileEncoding) --- End of inner exception stack trace --- at System.Web.UI.TemplateParser.ProcessException(Exception ex) at System.Web.UI.TemplateParser.ParseStringInternal(String text, Encoding fileEncoding) at System.Web.UI.TemplateParser.ParseString(String text, VirtualPath virtualPath, Encoding fileEncoding) --- End of inner exception stack trace --- at System.Web.UI.TemplateParser.ParseString(String text, VirtualPath virtualPath, Encoding fileEncoding) at System.Web.UI.TemplateParser.ParseFile(String physicalPath, VirtualPath virtualPath) at System.Web.UI.TemplateParser.ParseInternal() at System.Web.UI.TemplateParser.Parse() at System.Web.Compilation.BaseTemplateBuildProvider.get_CodeCompilerType() at System.Web.Compilation.BuildProvider.GetCompilerTypeFromBuildProvider(BuildProvider buildProvider) at System.Web.Compilation.BuildProvidersCompiler.ProcessBuildProviders() at System.Web.Compilation.BuildProvidersCompiler.PerformBuild() at System.Web.Compilation.BuildManager.CompileWebFile(VirtualPath virtualPath) at System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate) at System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate) at System.Web.UI.TemplateControl.LoadControl(VirtualPath virtualPath) at DotNetNuke.UI.ControlUtilities.LoadControl[T](TemplateControl containerControl, String ControlSrc) at DotNetNuke.UI.Modules.WebFormsModuleControlFactory.CreateSettingsControl(TemplateControl containerControl, ModuleInfo moduleConfiguration, String controlSrc) at DotNetNuke.UI.Modules.ModuleControlFactory.LoadSettingsControl(TemplateControl containerControl, ModuleInfo moduleConfiguration, String controlSrc) at DotNetNuke.Modules.Admin.Modules.ModuleSettingsPage.OnInit(EventArgs e) --- End of inner exception stack trace ---

**Comment by ChrisHammond** [comment]
Did you upgrade to DNN8? I don't think AF currently supports 8, but it is coming soon

**Comment by rossmick** [comment]
Chris

 

Sure did. I’ll see if I can go back a version in AF. Any idea when it will be ready for 8.0. For your info, everything seems to work fine in 8.0, except for Support and the captcha. Captcha just throws constant errors in event viewer.

 

Thanks for the reply.

 

H R Mickelson

**Comment by ChrisHammond** [comment]
You might subscribe to notifications on this particular issue here, @mitchelsellers has been working on the DNN8 release, but travelling a lot the last few weeks.

https://github.com/ActiveForums/ActiveForums/issues/369

**Comment by artfuld** [comment]
We should set up a disclaimer somewhere about this forum not to be installed on DNN8 or on a child page.

**Comment by mitchelsellers** [comment]
Version 6.2.3 of the forum resolves these issues
