### ISSUE TITLE
New release date estimate

### ISSUE THREAD

**Issue by rossmick** [ActiveForums/ActiveForums#375]
Would love to have an estimate on product release. Unfortunately, moved to DNN 8. and Active Forums destroyed itself with errors to the event viewer. Hopefully, I can reclaim some of the backup data and reconstitute the database when the new version comes out. Active forums was a very active module on out site and the members want it back ASAP. If I can help in testing just let me know. hrmickelson@gmail.com

**Comment by mitchelsellers** [comment]
I am working to try and get an estimate together.


A few outside factors, including the recent DNN security issues, have delayed my progress on this a bit


Mitchel Sellers
Microsoft C# MVP, DNN MVP
CEO/Director of Development
IowaComputerGurus, Inc.

Office: (515) 270-7063
Cell: (515) 707-3629
Fax: (866) 591-3679
________________________________

**Comment by frozendnn** [comment]
The story of AF's life.

**Comment by rossmick** [comment]
Mitch

 

Has anyone made any progress on getting Active Forum to work in DNN 8.0.3?

 

Thanks for any effort on this.

 

Have a great day.

 

Ross Mickelson

**Comment by mitchelsellers** [comment]
I have emailed Will asking about the "quick fixes" that he mentioned, but have not gotten a response.


I'm tabling my other work to try and get a release with ONLY that goal here as soon as I can.


Mitchel Sellers
Microsoft C# MVP, DNN MVP
CEO/Director of Development
IowaComputerGurus, Inc.

Office: (515) 270-7063
Cell: (515) 707-3629
Fax: (866) 591-3679
________________________________

**Comment by wmorgenweck** [comment]
Mitchel,
I didn't see an email from you.

I have everything done that needs to be done in order for it to work on DNN8.  This mainly involved swapping out some of the UI controls such as the number spinner. I'll try to get a pull request submitted tomorrow.

**Comment by mitchelsellers** [comment]
Will,


AWESOME!


I've sent multiple emails and not heard anything, I'll try to circle back, but if you can get a pull request in I'll expedite a package for everyone!!


________________________________

**Comment by frozendnn** [comment]
Anything new since last week?

**Comment by mitchelsellers** [comment]
I had a conversation with Will M. earlier this week.  He is going to work on getting a Pull Request submitted, I will release that Immediately as we then integrate the rest of the improvements.


________________________________

**Comment by rossmick** [comment]
Mr. Sellers

 

Thanks, I know our members are looking forward to getting it back on our club’s web site.

 

Have a great day.

 

H R Mickelson (Ross)

**Comment by rossmick** [comment]
Mike

 

Any forward movement on Active Forums. Seems like things are close and we just need a release. I am happy to test if you wish to put it out in a Beta.

 

Thanks for all the work.

 

H R Mickelson (Ross)

**Comment by mitchelsellers** [comment]
I haven't seen a pull request yet, I'm trying to clear my other "work in progress" to get a release out.  I'm dedicating tomorrow to this.


Mitchel Sellers

________________________________

**Comment by emo333** [comment]
First off I cannot express enough gratitude to you guys that have donated soooo much of your time to Active Forums as well as to open source projects as a whole.  

I have been anxiously awaiting for this as well...  I have several DNN7 sites that I have been waiting to go to DNN8 solely upon Active Forums functionality in DNN8.  I would be happy to test it in my environments and provide feedback, unit test results, etc...  I am limited in my skill set as to actually debugging but will try to the best of my abilities.  

Thanks,
Mitch (a different "Mitch")

**Comment by emo333** [comment]
Been testing new release on 8.0.4...  Only thing I have seen so far is trying to open the module settings blows it up.  So, can't access any basic module settings like module permissions...  Going to keep testing it out...

**Comment by mitchelsellers** [comment]
Do you by chance have a specific error

Mitchel Sellers
Microsoft C# MVP, DNN MVP

Office: (515) 270-7063
Mobile: (515) 707-3629

Sent from my mobile device. Pardon any brevity or autocorrect mishaps

On Sep 18, 2016, at 9:06 PM, Mitch <notifications@github.com<mailto:notifications@github.com>> wrote:


Been testing new release on 8.0.4... Only thing I have seen so far is trying to open the module settings blows it up. So, can't access any basic module settings like module permissions... Going to keep testing it out...

-

**Comment by rossmick** [comment]
Mitchel

I have installed the beta and it installed fine and have done minimal testing but all appears to work as advertise. I will continue testing and get back. I am really looking forward to the production version.

H R Mickelson (Ross)

**Comment by emo333** [comment]
Sorry bout being so vague..  Here is the skinny...

**Upon clicking "Settings" of AF module:**
![afsetbuttclick](https://cloud.githubusercontent.com/assets/18018621/18633025/54e2fe16-7e48-11e6-90d5-a278646edaac.png)

**Log of above:**
![afsetbuttclicklog](https://cloud.githubusercontent.com/assets/18018621/18633050/6a87528a-7e48-11e6-9714-6ca9a05f86b7.png)

Upon clicking "Edit Mode" with AF Control Panel up:
![afcontrolpanel-pageeditmodeclick](https://cloud.githubusercontent.com/assets/18018621/18633111/adff0c38-7e48-11e6-8f01-08dae6682d5a.png)

_Fresh install of:
Server 2012 R2 (fully updated)
  -IIS8.5
  -SQL Server 2014 Standard (same server)
  -DNN8.0.4 (blank)_

Let me know if you need anything more in depth or if you want me to try anything to test...  I can spin up another environment too if you prefer...

I am still testing and everything else I have tested works as expected (snappy too!).  I will post anything else I stumble upon.

Thank you for your efforts!!

**Comment by ChrisHammond** [comment]
I'm pretty sure, but not 100% yet on this, that this is caused by the Module targeting .NET 4.6 now

**Comment by mitchelsellers** [comment]
Closing this ticket in favor of a specific issue to document the version issue
