### ISSUE TITLE
Problem with poll - anyone with insight would be much appreciated

### ISSUE THREAD

**Issue by supermansrf** [ActiveForums/ActiveForums#376]
I'm not sure when this started. We don't use polls often.  For some reason, when we add a poll to a topic, the options run left to right instead of one on each line.   So I see:

Option 1             Option 2         Option 3       Option 4

Instead of 
Option 1
Option 2 
Option 3
Option 4

Anyone have any idea where to start? I've tried this on several of my forums but they aren't good tests as I usually copy templates across multiple sites.

**Comment by mitchelsellers** [comment]
Typically these are styles where there is a conflict from the skin to the template that removes the display block aspect of the elements.  If you have a link I can take a look

**Comment by supermansrf** [comment]
Activeforums.org you can see where I tested it there.  I don't know for sure but I'm being told by one of my site mods that this has worked before.  Can't say when.  It definitely doesn't follow the responsiveness like it should.  I feel like we tested this after the UI change was done but again I can't say for sure.

**Comment by supermansrf** [comment]
If you want a login for that let me know

**Comment by mitchelsellers** [comment]
Tested this with a clean installation of 6.3.2 and was not able to recreate!
