### ISSUE TITLE
Module Settings error (AF 6.3 for DNN 8)

### ISSUE THREAD

**Issue by sleupold** [ActiveForums/ActiveForums#380]
on a new install with Evoq Content 8.5.0 (DNN Platform 8.0.4), I am unable to enter Module settings.

**Comment by emo333** [comment]
I posted in issue#375 regarding same

**Comment by ChrisHammond** [comment]
I'm pretty sure, but not 100% yet on this, that this is caused by the Module targeting .NET 4.6 now

**Comment by ChrisHammond** [comment]
I've confirmed that this is the issue. In order to get this working on my DNN install I had to make a number of source changes to change the way references are setup, and the target framework for the module. I'll work on getting these changes into source control later this week.

**Comment by mitchelsellers** [comment]
@ChrisHammond Did your roll back to targeting .NET 4.5?  If so, are you planning a pull request for this?

**Comment by mitchelsellers** [comment]
Tested this on multiple DNN 9.x site and not having any issues at this point in time.
