### ISSUE TITLE
AF DNN 8.0 Beta Package Feedback

### ISSUE THREAD

**Issue by hismightiness** [ActiveForums/ActiveForums#382]
Has anyone run into any issues with the beta package yet?  Any show stoppers?

**Comment by IbrahimYM** [comment]
Well, yes!
DNN 9.0 on Azure.

AF still will not open the Settings dialog.
Exception: DotNetNuke.Services.Exceptions.ModuleLoadException: Unknown server tag 'dnn:DnnNumericTextBox'. ---> 

It's the same failure 8.XX versions were experiencing.

Also the MySettings fails with service unavailable.  It's probably a result of the settings not being accessed.

**Comment by emo333** [comment]
Strangely enough, I had same issue with the settings not being available but after a reboot of the webserver have had no more issues...

**Comment by IbrahimYM** [comment]
emo;
I tried to duplicate your experience by rebooting the website but got no joy! :(

Are you running 9 or 8.XX

**Comment by thabaum** [comment]
https://www.interactivewebs.com/blog/index.php/category/dnn-module/

taken from here this fixed my issue I had with an older installation.  Noticed it worked ok on a new installation.

This was missing from my web.config file directions taken from site are as follows:

The Fix

It is good practice to ensure that you have the latest version of the DotNetNuke forum module on your website. Especially if you are using the later versions of DNN.  Currently the module project has been moved into an open source project on GitHub. The latest version can be found here: https://github.com/ActiveForums/ActiveForums

 

 fixing the error

 you need to ensure that the web.config file also includes the following reference.

        <section name=”cryptography” requirePermission=”false” type=”DotNetNuke.Framework.Providers.ProviderConfigurationHandler, DotNetNuke” />

 

 

    <cryptography defaultProvider=”CoreCryptographyProvider”>

      <providers>

        <clear />

        <add name=”CoreCryptographyProvider” type=”DotNetNuke.Services.Cryptography.CoreCryptographyProvider, DotNetNuke” providerPath=”~\Providers\CryptographyProviders\CoreCryptographyProvider\” />

      </providers>

    </cryptography>

**Comment by IbrahimYM** [comment]
Thank you for your response Cody, but unfortunately your response does not cover my issue.

What it appears to comes down to is this:

The error: Unknown server tag 'dnn:DnnNumericTextBox' results from this control no longer being available.

The DnnNumericTextBox is now located in the following library:

C:\DNN90\Dnn.Platform-9.0.0\DNN Platform\DotNetNuke.Web.Deprecated\UI\WebControls\DnnFormNumericTextBoxItem.cs
  C:\DNN90\Dnn.Platform-9.0.0\DNN Platform\DotNetNuke.Web.Deprecated\UI\WebControls\DnnNumericTextBox.cs

I do not know why the RadNumericTextBox reference was moved into the Deprecated library, but the result is that this control is no longer available without including this library in a custom DNN Build. That is not an optimal solution.

What I do know is that DNN is moving to a new paradigm for Module Settings that includes the use of the Personas Toolbar. Perhaps AF should be considering a revamping of the module settings UI?

**Comment by Plumifrons** [comment]
I try to update AF 6.3.0 with 6.3.0 Beta (DNN 8.0.4) but the installation say that there is already a newer version installed what isn’t the case. What can I do to get it installed? 

On a fresh install the beta is working okay.

**Comment by Plumifrons** [comment]
It was the Active Forums What's New module. After removing the module I could install the Beta.

**Comment by IbrahimYM** [comment]
Glad you resolved your problem Plumiforms.  But my issue still remains unsolved.

**Comment by efficiondave** [comment]
Why was this released as 06.03.00 when there was already a 06.03.00 released in Oct of 2015? For sites that had already upgraded to the prior 06.03.00 site the changes need to be manually migrated as the Upgrade process says there's already a newer version.

**Comment by mitchelsellers** [comment]
Dave - This is intresting, as the version # was incremented.

Did you have a beta?

**Comment by efficiondave** [comment]
No, on the Releases page, https://github.com/ActiveForums/ActiveForums/releases there is a release of 6.3.0 from Oct 21, 2015.

**Comment by supermansrf** [comment]
He's right. There are 2 releases as 6.3.0. The new one should have been a new version.

**Comment by mitchelsellers** [comment]
I found the issue with this being an incorrect manifest update that didn't properly handle the second package in the manifest.  

Version 6.3.2, the most current release, will handle this properly!
