### ISSUE TITLE
Duplicate Posts and Email Notifications

### ISSUE THREAD

**Issue by hershope** [ActiveForums/ActiveForums#383]
I am having a problem with duplicate posts in my forum and as a result duplicate email notifications being sent to the users. Updated Active Forums to version 6.02.05 (Release Candidate) but the duplicate posts are still occurring. Changed the flood interval from the default 300 seconds to 30 seconds and that doesn't appear to have helped. Anyone experiencing the same issue and or know of a fix?

**Comment by mitchelsellers** [comment]
I am not able to recreate this issue with the current version of the product.  It is possible that a user with quick succession of posting could duplicate, but Version 6.3.0, and 6.3.1 did not show any issue.
