### ISSUE TITLE
Export Active Forums 6.2.4 (can't get to 8.0 just yet)...

### ISSUE THREAD

**Issue by PatrickMcCrann** [ActiveForums/ActiveForums#384]
After 10 years, our members have spoken...we need to move the forums out of our DNN site to a different provider.  We'll stay with everything else but can't do the forums and still run a business. 

A quick search tells me that there's no way in creation to get the AF database out (MYSQL?) to be used elsewhere...can anyone advise on this? 

Many, many thanks.

~ Patrick

**Comment by mitchelsellers** [comment]
A migration can be done, it just depends on the destination that you are going to.

The data from the Active Forums tables could be easily extracted from MSSQL, and then used with any other DBMS.

**Comment by PatrickMcCrann** [comment]
Mitchell, thank you. Is there documentation you could point me to? At this point my Developer sees the options as a full DNN back up file (not idea) or Forum CSV. I know you are busy, thanks in advance...

~ Patrick

**Comment by supermansrf** [comment]
There is no documentation for this process. You would be making something from scratch. The only thing that exists that I know of is a script that would convert the old DNN forum to Active Forums. 

While not impossible this would be a huge challenge. I'm working on merging 2 forums into one and it's a nightmare. Both are AF. I can't imagine going from one platform to another. You would have to know the structure of both forums really well. Or make sacrifices like archive things. Then you have the challenge of post authors and whatever your new membership is going to look like. You will have orphaned posts/replies unless user ID's aren't matched up. Again this all depends on your setup. 

Good luck regardless of what you do.

**Comment by PatrickMcCrann** [comment]
@supermansrf Thanks for the feedback...bummer that AF is so challenging. I was hoping we weren't the only ones who did this. 

I wish you luck as well!

~ Patrick
