### ISSUE TITLE
Add Reply/Quote to a Post/Comment are taking too much time

### ISSUE THREAD

**Issue by maduranga001** [ActiveForums/ActiveForums#386]
I am using DNN 7.4.1 version and trying to upgrade to 7.4.2+ version and failed. 
Anyway, I have only a few pages in the site. Home Page + Forum Page with AF and another few other pages. I am using Activeforums 6.2.4 version.

From a few months, the forum is taking too much time to load. Users have to wait for a long time to load the editor Reply or to quote. Now it is getting worse day by day.

Anyway, I just installed AF 6.3 on this site and crashed the site
I am using TurboScripts too and no luck.

I truncated the database and cleared the logs too. It was 2.2GB and it reduced to 1.6 now.

Please, can you help me why is this happening and how to fix this issue?

And what is the recommended HTML editor for AF?

Hope this could be same like this - (https://github.com/ActiveForums/ActiveForums/issues/358)
I saw this after posting this and when I am finding a solution. Anyway, I did not find a solution yet.

Appreciate if you can help.

**Comment by artfuld** [comment]
Do you get any errors in the eventlog?

**Comment by mitchelsellers** [comment]
In an effort to better track ActiveForums issues needing developer support I am closing this issue for the current time.  Future releases will focus on performance improvements.

If you have questions about a specific site, feel free to reach out to me directly.
