### ISSUE TITLE
6.3 - Configuration

### ISSUE THREAD

**Issue by joannschlosser** [ActiveForums/ActiveForums#387]
The configuration options available for 6.3 are different from those in the documentation I have for version 4.3.  I don't see the option to save attachments to the database.  Is this no longer available?

Thanks!

![capture](https://cloud.githubusercontent.com/assets/17364782/22632721/e329b9ee-ebe9-11e6-8682-fae1ad9bf8d8.PNG)

**Comment by Cambridgeport90** [comment]
I don't think so. I'll be testing myself soon, so I'll let you know if I find anything.

**Comment by mitchelsellers** [comment]
Looking at the version history, this was removed in the 5.x era versions of the Active Forums product.  

I support this, as database storage for files is not the best solution to support a wide variety of installations and usage.
