### ISSUE TITLE
Search the forums = "The service is unavailable."

### ISSUE THREAD

**Issue by prdsoftware** [ActiveForums/ActiveForums#388]
Whenever I search Active Forums, I get the error message "The service is unavailable."

Running AF 6.3.0, and it happens on DNN 7.0.4, DNN 8 and DNN 9

Any ideas on how to diagnose, or debug this?

Thanks

**Comment by supermansrf** [comment]
Have you tried turning search indexing off, saving and then back on?
Maybe do so with an app restart in between?

**Comment by prdsoftware** [comment]
Thanks for the suggestion.  Can you tell me where to find the indexing?  Is this in AF, or DNN?

**Comment by prdsoftware** [comment]
Checking the IIS logs, I see this.

Error 500

GET /Default.aspx TabId=118&afv=search&f=-1&q=this+is+my+search+criteria&rt=0&language=en-US HTTP/1.1

**Comment by supermansrf** [comment]
Module settings. Like where you would apply view permissions to the
module. There is an AF tab.

**Comment by prdsoftware** [comment]
Fixed!  That was it.  Thanks supermansft!  I toggled the "Full text searching" on/off and it worked.

Thanks again.

**Comment by mitchelsellers** [comment]
Closing this as the issue appears to be resolved.
