### ISSUE TITLE
2 versions of 6.3.0!?

### ISSUE THREAD

**Issue by prdsoftware** [ActiveForums/ActiveForums#389]
Hi all, as others have pointed out, (https://www.bountysource.com/issues/38667936-af-dnn-8-0-beta-package-feedback) there are 2 releases with an identical version number.  This is preventing updating to the latest, if you've already installed the former.

Is there likely to be an update to this soon?  What is involved in bumping up the version number to get a new build going?

Thanks

**Comment by mitchelsellers** [comment]
@prdsoftware I'm rolling a release tonight that will increment the version number to 6.3.1, for DNN 8.x only.

Upgrades should be fine for others with the name collision however, as you can use the "Repair" option on install.

**Comment by prdsoftware** [comment]
Thanks Mitchell.
