### ISSUE TITLE
Error installing Active Forums 6.03.02

### ISSUE THREAD

**Issue by malonzo77** [ActiveForums/ActiveForums#395]
I am receiving an error of "There is already an object named 'activeforums_Attachments' in the database. at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection," 
 it is coming from the first install of the 04.00.00.SqlDataProvider. Tried doing a repair install to no avail. 

Any ideas?

**Comment by artfuld** [comment]
@malonzo77 do you still have this problem? Was this an upgrade or a clean install?
