### ISSUE TITLE
Query String values not related to Active Forums don't survive the PostBack

### ISSUE THREAD

**Issue by bogdanez** [ActiveForums/ActiveForums#396]
Query String values not related to Active Forums don't survive the PostBack. 

Example URL (before submit): http://www.domain.com/activity/afv/post/aff/279/aft/20/afr/20/groupid/797?versiontest=123

URL (after submit): http://www.domain.com/activity/aft/20/groupid/797#33 (versiontest parameter is missing).

How can I keep these query string parameters after postback? Please help, it's breaking my site's functionality! 

P.S. Apologies for the tech support question, cannot find a better place to ask this.

**Comment by mitchelsellers** [comment]
Sadly, given the way that the forum module builds the URL this isn't something that is easily possible to address, and not something readily resolved in a future release.  I'm not aware of a workaround eitherl

**Comment by johnhenley** [comment]
https://weblogs.asp.net/scottgu/tip-trick-url-rewriting-with-asp-net

See section on post backs

John

On Apr 10, 2017, at 9:44 PM, Mitchel Sellers <notifications@github.com<mailto:notifications@github.com>> wrote:


Sadly, given the way that the forum module builds the URL this isn't something that is easily possible to address, and not something readily resolved in a future release. I'm not aware of a workaround eitherl

**Comment by mitchelsellers** [comment]
John,

Totally get it.  This just conflicts with the DNN UrlRewrite as a lot of that stuff is still there. 

This can be done, most likely, with s lot of effort. If someone would like to submit a pull request for it, after extensive testing of all URL permutations that would be great.

**Comment by johnhenley** [comment]
Ok. I must have misunderstood your previous message. Is it the DNN or forums rewriting code that is the culprit?

John

On Apr 11, 2017, at 9:03 AM, Mitchel Sellers <notifications@github.com<mailto:notifications@github.com>> wrote:


John,

Totally get it. This just conflicts with the DNN UrlRewrite as a lot of that stuff is still there.

This can be done, most likely, with s lot of effort. If someone would like to submit a pull request for it, after extensive testing of all URL permutations that would be great.

**Comment by mitchelsellers** [comment]
Really it's a combination. The rewrite stuff exposed in DNN doesn't provide an easy way to retain URL structures for unexpected values in the querystring. So we would most likely have to go around this. And there is substantial effort needed for this. 

Also, placing two modules with lots of dynamic actions can have other unintended consequences so we would have to test against conflicts etc to prevent another modules URL structure from impacting the forum.
