### ISSUE TITLE
DNN 9 

### ISSUE THREAD

**Issue by uba-tech** [ActiveForums/ActiveForums#403]
Is the latest version of ActiveForums DNN 9 compatible?

**Comment by mitchelsellers** [comment]
At this time people are using it on DNN 9, but extensive testing has not yet been completed

**Comment by zcoleman** [comment]
Curious if this has changed between August till now? We are looking to upgrade to DNN9 and I am trying to ensure that this module will be operational. Thanks!

**Comment by JaySMa** [comment]
I updated our development box from DNN 7 to DNN 9 and then installed AF without any issues.

**Comment by artfuld** [comment]
AF is compatible with DNN 9 if it is a domain site. There is some known problems with directory (child) sites
