### ISSUE TITLE
Not really a bug - Bottom of Dashboard reports "Active Forums 6.2.8.0"

### ISSUE THREAD

**Issue by JaySMa** [ActiveForums/ActiveForums#406]
Have AF 6.3.2 installed and at the bottom of the dashboard reports "Active Forums 6.2.8.0".

**Comment by johnhenley** [comment]
That is a bug that needs to be fixed. Check in the extensions list via host or admin menu and it should show 6.3.2.

**Comment by artfuld** [comment]
It uses reflection on the dll to show what version it is. And we haven't updated that assembly information since 6.2.8. This will be fixed with the next release :).
