### ISSUE TITLE
DNN 9.2.0 (build 349) breaks Active Forums?

### ISSUE THREAD

**Issue by jchristie07** [ActiveForums/ActiveForums#407]
I have a fresh install of DNN Platform 9.2.0 and successfully install the latest Active Forum module and when I place it on a page it throws an exception:

Message:Method not found: 'Boolean DotNetNuke.Entities.Modules.PortalModuleBase.HasModulePermission(System.String)'

However per the source code for DNN 9.2.0 HasModulePermission still exists.

**Comment by artfuld** [comment]
9.2 removed a lot of deprecated apis, this will be fixed really soon.

**Comment by artfuld** [comment]
#411 solves this
