### ISSUE TITLE
Change to height & width setting

### ISSUE THREAD

**Issue by jeffdanforth** [ActiveForums/ActiveForums#408]
https://github.com/ActiveForums/ActiveForums/blob/e5cf398461ef5db4ff947b7439f9d246ef00a2af/class/Polls.cs#L56

I would like to see this line change so that it uses style properties instead to make it more compatible with the responsive skins and bootstrap.

sb.Append("<img src=\"" + ImagePath + "/spacer.gif\" style=\"height:10px; width:" + Convert.ToInt32((BarWidth * dblPercent)) + "px !important;\" />");

Jeff

**Comment by artfuld** [comment]
This should be a rally easy change. But does it matter? From what I understand (I''m a backend developer so please correct me if I'm wrong) style will always take precedence over in line width and height so having the widht and height on the img-tag or having it inside a style shouldn't be any different.
Do you have a page where I can see where this is a problem?

**Comment by jeffdanforth** [comment]
Hi, you can see the issue here: http://www.pachc.org/Membership/Organizational-Membership/Test-Forum/aft/50.  On our development server I change the source code and recompile using the style settings and the bars appear as they should.

**Comment by artfuld** [comment]
So it seems that you have some other css that is using !important and that's the reason why your staple isn't showing correctly. Changing to style inside that will probably not hurt anyone as it is a local style only.

Unless anyone have any other saying on this it should be implemented for the next release.
