### ISSUE TITLE
Active Forums and DNN 9.2

### ISSUE THREAD

**Issue by wmorgenweck** [ActiveForums/ActiveForums#410]
Just a heads up, Active Forums doesn't work with DNN 9.2.  Looks like it was still using some of the deprecated APIs that were removed.

**Comment by jchristie07** [comment]
Looks like it has to do with getting permissions from the current user to show the options and edit buttons - what were these API's changed to do we know?

**Comment by artfuld** [comment]
Currently changing every deprecated api for af to work with 9.2. Just got some testing of the forum to do and I'll do a pull request.

**Comment by artfuld** [comment]
#411 get's the forum working with DNN9.2
