### ISSUE TITLE
JS error in DNN9.2.2 - with fix.

### ISSUE THREAD

**Issue by vincentparrett** [ActiveForums/ActiveForums#417]
I'm seeing a js error in quickedit.ascx caused by this code

`<script type="text/javascript">
    jQuery(function ($) {
        $('#aftopicedit').dnnTabs();
    });
</script>`

I managed to fix the problem by adding the following line to Classic.ascx.cs in the Setup method 

`ClientAPI.RegisterClientReference(this.Page, ClientAPI.ClientNamespaceReferences.dnn);`

This should be before the call to `Framework.jQuery.RequestDnnPluginsRegistration()`

I would submit a PR, but my version is already changed from the default to fix theme issues (removing use of font-awesome).

**Comment by artfuld** [comment]
Adding this to the next release.
