### ISSUE TITLE
Breadcrumb at the top of the forum page

### ISSUE THREAD

**Issue by hismightiness** [ActiveForums/ActiveForums#435]
There is a breadcrumb to help navigate the forums at the bottom of the view, but not at the top.  This update proposes that the breadcrumb is in both places, with the new (additional) position being at the top of the view as well.  

This includes the quick nav drop down menu.  :)

**Comment by allanedk** [comment]
You can achieve this by adding breadcrumb-code to the templates using the AF-admin.

I've added this to the "Topic"-template:

```
<ol class="breadcrumb">
    <li class="breadcrumb-item">[FORUMMAINLINK]</li>
    <li class="breadcrumb-item">[FORUMGROUPLINK]</li>
    <li class="breadcrumb-item active">[FORUMLINK]</li>
</ol>
```

**Comment by hismightiness** [comment]
Hmmm... I'm not able to update that. 🤔

**Comment by hismightiness** [comment]
When I click to save the first time, it says it was done successfully. If I make any changes, nothing happens.  When I look at the console, there's an error logged each time I press `<Enter>` and after the first save, each time I click to save again.

**Comment by hismightiness** [comment]
![image](https://user-images.githubusercontent.com/938023/59442080-65028280-8dae-11e9-97a7-2172b89ceef9.png)

**Comment by hismightiness** [comment]
When I look in the database, the TopicView in the database, I see the setting is saved, but I don't see it on the view itself when I view the forums again.  :( 

![image](https://user-images.githubusercontent.com/938023/59442229-aa26b480-8dae-11e9-815c-ead4f64c1ac6.png)
