### ISSUE TITLE
Posts show twice

### ISSUE THREAD

**Issue by hismightiness** [ActiveForums/ActiveForums#441]
All of a sudden, I'm seeing my posts appear in the forums twice.  I have no idea why.  I've tried quick reply and normal reply.  The post is only there once.  If I delete either instance of the post, they're both deleted.  

Example URL:  
https://dnncommunity.org/forums/aft/64  

I use two different Chrome browsers, each logged in with a different Google account.  In one, I'm logged in as a superuser and the other I'm just a standard user.  The latter is the only one I use to post.  However, I recently created this normal user and attempted to map the previous superuser activity to this new user account.  Perhaps I missed one of the database tables?

Does anyone have any proven/tested SQL scripts that I can review to see what I may have missed?

**Comment by hismightiness** [comment]
![image](https://user-images.githubusercontent.com/938023/59941750-de375080-9412-11e9-84ea-11b9d6dafecb.png)

**Comment by artfuld** [comment]
It's really really strange that only you get it, when Jeff posts it's only once :/.

**Comment by hismightiness** [comment]
Agreed.  I'm a bit perplexed.  I'm only responding using the non-superuser account, and I'm not doing anything but using the reply and quick reply.  :(

Just in case it helps...  I've created the following query based on the tables that have data.  

```
DECLARE @OldUserId INT, @NewUserId INT;

SET @OldUserId = 1;
SET @NewUserId = 2;

UPDATE [dbo].[activeforums_Likes] SET UserId = @NewUserId WHERE UserID = @OldUserId;

UPDATE [dbo].[activeforums_Content] SET AuthorId = @NewUserId WHERE AuthorId = @OldUserId;

UPDATE [dbo].[activeforums_Forums] SET LastPostAuthorId = @NewUserId WHERE LastPostAuthorId = @OldUserId;

UPDATE [dbo].[activeforums_Forums_Tracking] SET UserId = @NewUserId WHERE UserId = @OldUserId;

UPDATE [dbo].[activeforums_Likes] SET UserId = @NewUserId WHERE UserId = @OldUserId;

UPDATE [dbo].[activeforums_Subscriptions] SET UserId = @NewUserId WHERE UserId = @OldUserId;

UPDATE [dbo].[activeforums_Topics_Ratings] SET UserId = @NewUserId WHERE UserId = @OldUserId;

UPDATE [dbo].[activeforums_Topics_Tracking] SET UserId = @NewUserId WHERE UserId = @OldUserId;

UPDATE [dbo].[activeforums_UserProfiles] SET UserId = @NewUserId WHERE UserId = @OldUserId;
```

**Comment by hismightiness** [comment]
Argh!  Now my posts are happening in three's!  :(

**Comment by hismightiness** [comment]
I think I found the culprit!  In reviewing the data, I looked for any tables that appear to have duplicate content, and the `UserProfiles` table has three records for my user account.  Could this be the issue?  Does anyone know how the profile record gets created?

**Comment by sleupold** [comment]
User Profile has a record for each profile property (see profilepropertydefinition table)

**Comment by hismightiness** [comment]
In the forums, @sleupold ?

**Comment by sleupold** [comment]
ah, you are talking about activeforums_userprofiles table. this should have a single row per user and portal  (moduleID is always -1, preventing a foreign key constraint). 
Unfortunately, the indexes are crap and do not enforce profiles to be unique per user and portal.
please check stored procedures activeforums_UserProfiles_Save and activeforums_UserProfiles_create, which should prevent duplicate profiles.

**Comment by sleupold** [comment]
btw. I haven't seen it in AF on our sites (running AF version 6.3.0)

**Comment by hismightiness** [comment]
@sleupold  Well, if the indexes are crap, are we expecting a PR from you?

**Comment by hismightiness** [comment]
By the way, removing the duplicate user profile records in the database resolved this.

**Comment by artfuld** [comment]
I have never seen or heard of this before either. Nice that you fixed it!
