### ISSUE TITLE
View All Forums

### ISSUE THREAD

**Issue by hismightiness** [ActiveForums/ActiveForums#444]
Many of us are used to or would like to be able to look at all of the forum posts at once.  For example in the previous "core" forums module, there was a forum at the top that allowed you to do just that.  Is it possible to add this as a feature?

Reference:  https://dnncommunity.org/forums/aft/72

**Comment by sleupold** [comment]
you may use "Active Forums What's New" - either by latest posts or threads (see e.g. https://www.trans-ocean.org/forum/neu and https://www.trans-ocean.org/forum/neu2)

**Comment by hismightiness** [comment]
@sleupold  Hmmm... I don't see that.  It that a feature that I need to enable (and missed)?

**Comment by sleupold** [comment]
it is an additional module, should be included in the package (it is still listed in the manifest)

**Comment by ChrisHammond** [comment]
What about the Active Topics thread?

https://dnncommunity.org/forums/afv/grid/afgt/activetopics/ts/80640
