### ISSUE TITLE
Post crash when Theme code is posted

### ISSUE THREAD

**Issue by Timo-Breumelhof** [ActiveForums/ActiveForums#452]
An example Theme code crashed the Forum post.
I'll test and post more info on what the exact issue is

**Comment by hismightiness** [comment]
Thank you for opening and closing this.  😉 😜 🤣

**Comment by Timo-Breumelhof** [comment]
I found out I made a mistake.
Both in understanding how the module works and a template.
I accidentally copied the [POSTINFO] token to the TopicView template which caused and endless loop and thus the 503.
Also I found out that when you edit a template and switch to "default" the module still uses the edited template.

**Comment by hismightiness** [comment]
No worries.  I just thought it was funny.  😆
