### ISSUE TITLE
Looking for additional project coordinators

### ISSUE THREAD

**Issue by jbrunken** [ActiveForums/ActiveForums#57]
I think with a few active developers contributing fixes and enhancements, this project could make some significant headway fast.  As some of you have probably notices, I don't always have sufficient time to dedicate to this project and I don't want to be the one holding it up.

So, I would like to find one more two more people to help coordinate releases going forward.

Potential coordinators must have:
- A basic understanding of the Active Forums project
- A good understanding of Git/Github (including the merge/pull request process)
- A good understanding of the DNN module packaging process.

If this describes you and you're interested in taking a more active role in helping this project move forward, please contact me ASAP. 
##

**Comment by artfuld** [comment]
Closing this as we have a new topic regarding this. #409
