### ISSUE TITLE
Anonymous Users Issue

### ISSUE THREAD

**Issue by frozendnn** [ActiveForums/ActiveForums#62]
I allow anonymous users to post on my website. The anonymous users get to input their "username" and post. They can still do it. However, now in the Latest Topic view and everywhere (but the topic view) instead of displaying their "username" it uses the term Anonymous. 

Instead of saying Started by Halle Berry it says Started by Anonymous. 

This has recently happened. When the Latest Topics template was changed from the old template. 

Jason, can you pleas undo this change? Can you please look into it? Thanks. 
##

**Comment by ericktj** [comment]
Hello, I'm currently using version 6.1.5 which is the latest one so far, and I would like to set anonymous users to Reply, I'm having issues trying to do it within the Control Panel or Module Settings

On Control Panel it just won't let you change any of the permissions
On Module Settings it lets you select anonymous users to reply but when Update nothing changes, I get back to Module Settings and Anonymous users is unchecked 

Can somebody provide some help on this issue ?

Thank you very much

**Comment by frozendnn** [comment]
Any progress on this one? I know this is a low priority since most of you do not allow anonymous posting but maybe it is an easy/quick fix?

**Comment by artfuld** [comment]
What I can see this is only in topicsview, everywhere else the name entered is shown. @frozendnn  Do you want it shown some way that the user that has posted is an anonymous user?

**Comment by artfuld** [comment]
Does anyone else have any input regarding this? It's fairly easy to just show the displayname if it can't find the name from the users database. I will have it show the name as is and if someone have any problems with it just let me know and I'll have it fixed for another release.
