### ISSUE TITLE
Wrong editor in mobile devices

### ISSUE THREAD

**Issue by Plumifrons** [ActiveForums/ActiveForums#8]
In a mobile device I only seen the text editor and not the standard DNN editor. 
(nice to have)
##

**Comment by artfuld** [comment]
There is a code-snippet in af checking if it's a mobile device and this then sets the editortype to be textbox instead of the choosen editor.

Shouldn't be a problem to delete the 4 rows that does this but as someone stated before, this was done because not all mobile devices could handle the rich text editor.

**Comment by artfuld** [comment]
Seeing the result with the default dnn editor, I'm not sure this would be a great idea. Maybe if we could switch to a simplified version of the editor when it's mobile.
![image](https://cloud.githubusercontent.com/assets/6116748/9129901/8703a81c-3cdd-11e5-9a81-2056c69f5be5.png)

**Comment by artfuld** [comment]
And right now it seems like this can only be done in core dnn, atleast with the radeditor.

**Comment by artfuld** [comment]
Ok, I've added another option for the editor, and this is mobile device. So now you can manually set for any group if the mobile device should use the standard texteditor or the dnn editor.
![image](https://cloud.githubusercontent.com/assets/6116748/9131692/2bb6e3be-3cee-11e5-90bd-6cb62f97198d.png)
If you feel that the toolbars is too much for a mobile device then you have to change that in dnn for every richtexteditor (host -> advanced -> Rich Text Editor Manager)

I will add this as a pull and Seth will have to decide if it should be implemented or not.

**Comment by Plumifrons** [comment]
Great job, I like that. I use the latest Telerik editor and they are getting better every new version. Better than the one shipped with DNN.
