### ISSUE TITLE
Incorrect time stamp

### ISSUE THREAD

**Issue by creativeavatar** [ActiveForums/ActiveForums#94]
It appears that an old Active Forums issue has reappeared. The time stamps are not showing correct our website only for active forums. The portal is setup for PST and we're showing a 7 hour difference from what it should be. I.e. when it's 10am, it's showing 5pm. This is only happening with Activeforums, all other modules on the site such as the journal are working correctly. 

This happens regardless of friendly urls are turned on or off. The site is running on Azure websites. Any help on this would be greatly appreciated! 
##

**Comment by artfuld** [comment]
@creativeavatar do you still have this issue?
